### ISSUE TITLE
[Question] Why don't I see any KEYS (records) in Redis when my sockets are connected?

### ISSUE THREAD

**Issue by crobinson42** [socketio/socket.io-redis#104]
I'm using sails.js with socket.io-redis and everything is working perfectly.. I'm confused why I don't see any keys in my Redis store for the connected sockets. If I change `db` to a string or another integer I still don't see anything in Redis. Any light to shed on this? Thanks!

my socket config:
```
adapter: 'socket.io-redis',
  host: '127.0.0.1',
  port: 6379,
  db: 0,
  pass: ''
```

**Comment by LordMajestros** [comment]
Socket.io-redis doesn't use keys. I think it uses pub sub channels.

**Comment by crobinson42** [comment]
@LordMajestros You're right, **thanks**!

I'm able to view the PubSub channels in Redis-cli with the following command: 
`$ redis-host:6379> PUBSUB CHANNELS`

**Comment by raulferras** [comment]
Could this be added to the documentation? I had the same problem while checking if everything was working as expected.

**Comment by botondev** [comment]
Hi, 8 years later, I have a similar issue, but I do not even see the channels when I list it. However, everything works on the app side. Anyone any ideas what should I look for?

**Comment by darrachequesne** [comment]
@pherrymason here we go! https://socket.io/docs/v4/redis-adapter/#is-there-any-data-stored-in-redis
