### ISSUE TITLE
But how to listen to saved-socked-id ? 

### ISSUE THREAD

**Issue by cemozturk** [socketio/socket.io-redis#106]
It's easy to emit/broadcast from a different process to other by socket-id, but i couldn't figure out how to listen a socket -id from an another process ?

Should i maintain my own messaging layer with redis pub/sub to listen events from another process/cluster ? 

Also what about redis pub/sub performance ? For example, what if i send transformation object of a rolling ball from unity client to server with 50 messages per second ?

I mean, ok we handle more clients with redis but do we kill  performance by heavly sit upon redis pub/sub communication ?

Thank you.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
