### ISSUE TITLE
Support for Sentinel Clustering

### ISSUE THREAD

**Issue by chadams** [socketio/socket.io-redis#108]
I don't see any documentation for supporting clustered Redis Instances. Is this supported?

**Comment by magicdawn** [comment]
this module use redis only for pub/sub. not storage.

**Comment by darrachequesne** [comment]
The default redis client, [node_redis](https://github.com/NodeRedis/node_redis), does not support Cluster.

But since v1.1.0, you can now provide an [ioredis](https://github.com/luin/ioredis) client, which does support Cluster/Sentinel out of the box:

```js
var redis = require('ioredis').createClient;
var adapter = require('socket.io-redis');
var pub = redis(port, host, { auth_pass: "pwd" });
var sub = redis(port, host, { return_buffers: true, auth_pass: "pwd" });
io.adapter(adapter({ pubClient: pub, subClient: sub, subEvent: 'messageBuffer' }));
```

**Comment by darrachequesne** [comment]
@aryeharmon my example was missing the `var io = require('socket.io')(3000);` line obviously, I updated it.
