### ISSUE TITLE
Is this scales good? 

### ISSUE THREAD

**Issue by magicdawn** [socketio/socket.io-redis#110]
I notices that
- the `rooms` / `client` data stores in memory. 
- the redis instance is used for pub/sub. for emit events between different processes

so with this adapter. I'm still storage data in memory. but the `socket.io-adapter` says

> This module is not intended for end-user usage, but can be used as an interface to inheirt from from other adapters you might want to build.

So I'm asking is this module scales good?

**Comment by magicdawn** [comment]
or just I'm missing some info. some module does use redis for storage ?

**Comment by darrachequesne** [comment]
You are right, socket objects are still kept in memory, redis is just used to broadcast messages accross servers.

Yet, as more server means you can handle more clients (along with handling node failures and such), that should scale pretty well.
