### ISSUE TITLE
No way to use Redis protected with password

### ISSUE THREAD

**Issue by nesanjoseph** [socketio/socket.io-redis#111]
Hi,

What should be done in the following usage snippet if I have to use a **_Redis protected with a password_**?

`var io = require('socket.io')(3000);`
`var redis = require('socket.io-redis');`
`io.adapter(redis({ host: 'localhost', port: 6379 }));`

Is there way already which I am not  aware of?

Thanks,
Nesan Joseph.

**Comment by jackycute** [comment]
Here it is (maybe)
https://github.com/socketio/socket.io-redis#custom-client-eg-with-authentication

**Comment by nesanjoseph** [comment]
Many thanks, this is going to solve the issues for me. 

I also see that the following Pull request, if merged, should solve the problem much simpler and the initialization will be much simpler.
https://github.com/socketio/socket.io-redis/pull/97

This issue can be closed.
