### ISSUE TITLE
Binary Not Working

### ISSUE THREAD

**Issue by IsaiahJTurner** [socketio/socket.io-redis#112]
On the primary server the client receives an ArrayBuffer but on servers receiving events through redis, their clients receive an object `{_placeholder: true}`

**Comment by Trainxy** [comment]
I have the same trouble too.

If sender and receiver in same server, the receiver client receive the `Binary Frame`. But other receiver deployed on other servers only receive the string `{_placeholder: true, num: 0}`.

Is there problem with msgpack or redis pub/sub? I'm puzzled.

**Comment by LordMajestros** [comment]
I'm not sure binary data is supported by the node.js redis client. I know the scala client doesn't https://github.com/debasishg/scala-redis/issues/112

**Comment by IsaiahJTurner** [comment]
Would anyone be willing to take this on for a bounty? Just react with thumbs up if you would. I don't want to post it if nobody is going to do it.
