### ISSUE TITLE
Example to use socket.io-redis

### ISSUE THREAD

**Issue by rifton007** [socketio/socket.io-redis#115]
Hi all and thanks for your time and your help.

I need a simple example for use socket.io-redis, with comments please.
I read the documentation, but I did not understand.
Thank you,

**Comment by darrachequesne** [comment]
`socket.io-redis` does just extend the default in-memory adapter, nothing more.

```javascript
var io = require('socket.io')(3000);
var redis = require('socket.io-redis');
io.adapter(redis({ host: 'localhost', port: 6379 }));
```

Every message sent is broadcast accross every server connected to the redis backend. Please see the sample chat [here](https://github.com/socketio/socket.io/tree/master/examples/chat).

**Comment by Merlin-Xu** [comment]
how to emit  or broadcast a message to others ?just like socket.emit("message",msg) and socket.broadcast("message",msg) in socket.io. I am not clear about it .

**Comment by Merlin-Xu** [comment]
I use pm2 -i to start my socket server (bind express) by 4 workers .And use socket.io-redis as your code
but in same namespace **sometimes** the clients couldn't send/receive msg  each other. So what's the Keys in Redis. How to send to other worker's client?

**Comment by akprats33** [comment]
@Merlin-Xu Did you find any solution to your problem ? I am facing similar issue. Emit might be triggered in some cluster and sometimes clients don't receive the data.

**Comment by Merlin-Xu** [comment]
@akprats33  Give up! replace it with others. I used other tools ,like kue and ribbit to manage them. Work fine.

**Comment by akprats33** [comment]
@Merlin-Xu Thanks for the response.
