### ISSUE TITLE
reverse

### ISSUE THREAD

**Issue by awdogsgo2heaven** [socketio/socket.io-redis#120]
So this library allows you to emit a message to all clients attached to any Node process hooked to this redis server. I have a need to do something somewhat of reverse.  I'm using ELB / AWS and as a result, can not determine what server will be chosen when a user connects. However, I have a process that needs to receive messages from Multiple users. This process would be created on any one of the servers, and the users it needs to listen to could connect to any one of the other servers. So essentially what needs to happen is, if a user emits a message to a server it needs to be forwarded along to the correct server listening for the said event (it could be a specific room the users are in). I'm confident Redis- pub sub can achieve this but not really sure if Socket.IO's adapter could accommodate this. (is there a hook for a message incoming from a client?)

This feature might be too unique to be considered worth adding to your repository, but wanted to throw it out here if someone has a proposal on how this could be done inside the adapter, I'm willing to create a pull request or a fork. 

Since this might be mentioned, one might be tempted to suggest 'sticky sessions' but this requires another proxy and introduces single points of failure and really unnecessary for what I'm trying to achieve.  I also don't think this would be any less perform-ant than what the current adapter achieves.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
