### ISSUE TITLE
Understanding what redis is actually doing behind the scenes.

### ISSUE THREAD

**Issue by nateholmes3** [socketio/socket.io-redis#121]
I am hoping for a step by step process of exactly what socket.io-redis does to allow users to emit messages to other users that have a socket connection on a different server than them.

**Comment by awdogsgo2heaven** [comment]
I am not a contributor, but from reviewing the source, it essentially does this:

1. Subscribes to redis 'channels' that are created for rooms/namespaces?. 
2. When you broadcast/emit a message Server side, it then uses redis's publish feature to send the message to all of the channels. 
3. It then forwards that message to respective clients.

This requires all the instances to be connected to the same redis instance.
It really comes down to just being a shared Event Emitter across all node instances, allowing Socket.IO to forward messages broadcasted by another instance.
