### ISSUE TITLE
intermittent issue: events emitted multiple times to single client in seeming infinite loop

### ISSUE THREAD

**Issue by r3wt** [socketio/socket.io-redis#124]
nginx reverse proxy
single node (currently)
redis backend to socket-io (this package)
custom pub/sub client
redis cluster (3 instances)

affected client:
socket.io swift client.

issue: on some occasions the client emits/receives events multiple times until stackoverflow on the client. this issue doesn't occur in the simulator, but when compiling the app and testing on the phone it occurs intermittently.

**Comment by r3wt** [comment]
ok, so we eliminated the dupe connections in swift, and now what we are seeing is this:

1 connection, 1 emit
2 received emits at the client. 

This seems to indicate the local server is emitting to the room directly, then pub to redis, which is then picked up by the redis sub and emitted again.

**Comment by darrachequesne** [comment]
Hi! Could that be linked to https://github.com/socketio/socket.io-redis/pull/76?

> This seems to indicate the local server is emitting to the room directly, then pub to redis, which is then picked up by the redis sub and emitted again.

Seems weird, it should be prevented by: https://github.com/socketio/socket.io-redis/blob/master/index.js#L110

**Comment by r3wt** [comment]
@darrachequesne you have to publish a release for people to benefit from it. a release hasn't been published since december

**Comment by darrachequesne** [comment]
Did the last release fix your issue? Else, could you provide a simple test case reproducing the behaviour please?

**Comment by darrachequesne** [comment]
Closing for now, please reopen if needed.
