### ISSUE TITLE
Joining socket room from instance that doesn't have the socket in memory.

### ISSUE THREAD

**Issue by jreeter** [socketio/socket.io-redis#125]
We have a multi process socket service that is backed by a message based **queue**, so I can't guarantee which socket instance gets the messages. Naturally, socket.io-redis is what I am needing so I can perform emits across any instance so it can reach the client. This part works. What I am having problems with is telling socket clients to join or leave rooms across instances, is this possible?

``` javascript
seneca.add({role:'sockets', cmd:'leaveRoom', accountId:'*', podId:'*'}, function(args, done) {
        return seneca.actAsync({role: 'session', cmd: 'read', key: args.accountId})
        .then((session) => {
            if(session && session.socketId) {

                // I need to tell the socket with id session.socketId to leave a certain room
            }
        })
        .catch(seneca.log.error)
        .finally(() => {
            done();
        });
    });
```

**Comment by jreeter** [comment]
+1 bump

**Comment by darrachequesne** [comment]
Hi! You may be able to catch the messages sent from the underlying adapter by overriding the `Socket#packet` method here: https://github.com/socketio/socket.io/blob/master/lib/socket.js#L218

See https://github.com/socketio/socket.io-adapter/blob/master/index.js#L132

**Comment by infnada** [comment]
Could this help? I'm still searching a "community" solution for this case:

https://github.com/socketio/socket.io/issues/2458
