### ISSUE TITLE
1.10.0 crashes sub.duplicate is not a function

### ISSUE THREAD

**Issue by jezell** [socketio/socket.io-redis#127]
Pulled down latest during build and app started crashing

```
+-- socket.io@1.4.8
| +-- socket.io-adapter@0.4.0
| | `-- socket.io-parser@2.2.2
| `-- socket.io-parser@2.2.6
+-- socket.io-client@1.4.8
+-- socket.io-redis@1.1.0
```

```
/usr/src/app/node_modules/socket.io-redis/index.js:57
  var subJson = sub.duplicate({ return_buffers: false });
                    ^

TypeError: sub.duplicate is not a function
    at adapter (/usr/src/app/node_modules/socket.io-redis/index.js:57:21)

**Comment by darrachequesne** [comment]
Hi! Which redis client are you using? Which version? The default one?

**Comment by jezell** [comment]
redis-sentinel, looks like io-redis has same problem.

**Comment by darrachequesne** [comment]
It seems ioredis does define a `duplicate` method: https://github.com/luin/ioredis/blob/c87dae642ab0d3905323e33f80939a33bbecb2d1/lib/redis.js#L355

So it should not affect this implementation :angel:

**Comment by jezell** [comment]
Confirmed switching from redis-sentinel to io-redis solves problem with 1.1.0. Seeing that redis-sentinel is a bit old, probably a good idea to do anyway. Was receiving the same error message when I tried quick switch to io-redis, but looks like that was actually being caused by passing wrong constructor params.

**Comment by bf** [comment]
Yeah our production servers also started crashing after this update was pulled with a ^1.0.0 config of socket.io-redis. Not good.

**Comment by darrachequesne** [comment]
@bf to be fair, the Readme clearly states:

> If you decide to supply pubClient and subClient, make sure you use node_redis as a client or one with an equivalent API.
