### ISSUE TITLE
Rooms with multiple node processes

### ISSUE THREAD

**Issue by pravincar** [socketio/socket.io-redis#13]
How do I get the list of connected clients in a particular room across nodes. 

 io.sockets.adapter.rooms seems to have the list of clients only in a specific room.

**Comment by aravindsrivats** [comment]
Is this feature available?

**Comment by fgodino** [comment]
I created a PR that adds this functionality and is up to date with the current Adapter. Check it out https://github.com/socketio/socket.io-redis/pull/109

**Comment by artofspeed** [comment]
@fgodino can i safely use socket.rooms to get all the rooms a socket has joined?

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/commit/679e73ce6e88a50e418dcd865c4fb9d69aca6feb
