### ISSUE TITLE
sub.duplicate is not a function

### ISSUE THREAD

**Issue by mbobrovsky** [socketio/socket.io-redis#131]
After update I have got this message: 

> var subJson = sub.duplicate({ return_buffers: false });
> TypeError: sub.duplicate is not a function

But return_buffers I set to true:
`const redisClient = redis.createClient;
const pub = redisClient(config.redisPort, config.redisHost, {auth_pass: config.redisPass});
const sub = redisClient(config.redisPort, config.redisHost, {return_buffers: true, auth_pass: config.redisPass});`

**Comment by mbobrovsky** [comment]
Oh, it's Ok. after update redis this bug was hide

**Comment by darrachequesne** [comment]
@mbobrovsky glad you found a solution! Can you close the issue then?
