### ISSUE TITLE
Emitting to all sockets in a room in current instance

### ISSUE THREAD

**Issue by KristjanTammekivi** [socketio/socket.io-redis#135]
Hey, so here's my use case:

I have a socket.io server, which listens for changefeeds from RethinkDB and passes the messages to the clients that are in a specific room. This server runs in 2 instances. Some upcoming functionality however requires me to use the redis adapter for shared rooms and because of that, every changefeed message would be sent twice. Is there a way I can only emit to the current instance sockets?

I could use an MQ in front to make sure that each changefeed message is sent once, but that would only add further complexity, so hopefully there's a built in solution.

**Comment by darrachequesne** [comment]
Would the solution proposed [here](https://github.com/socketio/socket.io-redis/pull/119) answer your need?

**Comment by KristjanTammekivi** [comment]
That's exactly what I need, thanks! 👍
