### ISSUE TITLE
Please do not create a redis client on your own

### ISSUE THREAD

**Issue by Meaglin** [socketio/socket.io-redis#138]
In our project we elegantly close our server by closing all open connections.
Socket.io-redis is breaking this here:
https://github.com/socketio/socket.io-redis/blob/master/index.js#L57
by creating connections without leaving a public reference.

Please fix, we cannot upgrade to the new version because of this.

**Comment by darrachequesne** [comment]
@Meaglin as usual, PR is welcome!

**Comment by Meaglin** [comment]
I understand, but this was not broken before.

**Comment by darrachequesne** [comment]
@Meaglin we could maybe add a cleanup method, calling `quit()` on each redis client, or try to remove the `subJson` altogether. What do you suggest?

**Comment by Meaglin** [comment]
I recommend storing references on the client, so people can decide themselves what to do with them

**Comment by gboysko** [comment]
So, is it fair to say that today when still do not have a clean shutdown because the `pubClient` and `subClient` each hold open connections to the Redis Server? And there is no propagation from the socket.io `Server` close to the adapters?

FWIW, I'm still using the 4.0.1 version of `socket.io-redis`.

**Comment by mishelen** [comment]
Agreee. 
This is by the way not useless nonsense. Look, for example, on Heroku for one Redis plugin, the amount of memory is fixed, but also a fixed number of connections and no more to receive. When restarting a cluster, there may be unclosed connections. And they will not let it open the new connections.
