### ISSUE TITLE
Socket.io with cluster

### ISSUE THREAD

**Issue by Aeonrush** [socketio/socket.io-redis#144]
Hi
[Here a Gist](https://gist.github.com/AeonRush/ee01e3fcdd336a70c62409f1b0f55394) with sample.
When I run it I have a multiply `time` event on client. I tried a `cluster` and a [`sticky-session`](https://github.com/indutny/sticky-session) but result the same.
Maybe I doing something wrong?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
