### ISSUE TITLE
Using .end() without the flush parameter is deprecated and throws from v.3.0.0

### ISSUE THREAD

**Issue by chemerisuk** [socketio/socket.io-redis#149]
After updating to socket-io 1.6.0 I see many messages like below:

> [WARN] node_redis: Using .end() without the flush parameter is deprecated and throws from v.3.0.0 on.
Please check the doku (https://github.com/NodeRedis/node_redis) and explictly use flush.

Any idea how to fix this issue?

**Comment by darrachequesne** [comment]
Hi! I did not see any call to the `end()` method in the code here, maybe there are in your own code? (or am I somewhat blind?)

Also, I do not think it is related to socket.io 1.6.0, but rather after upgrading `redis` to `2.6.x` (https://github.com/NodeRedis/node_redis/blob/ff9b727609ea125919828f7373e40082fd432eec/lib/extendedApi.js#L55)

**Comment by chemerisuk** [comment]
You are totally right the problem was in my code indeed. Thank you for the help!

**Comment by weifansym** [comment]
This warn comes from redis, when you use end() method.
[node_redis](https://github.com/NodeRedis/node_redis)

**Comment by Senior-Hayato-Suzuki** [comment]
Thanks!!!
Great.
