### ISSUE TITLE
subEvent seems doesnt work

### ISSUE THREAD

**Issue by DiegoHuang** [socketio/socket.io-redis#150]
Hi,
I set opetion.subEvent as 'RedisPub', but it still receive event from 'message', 
sample code as belowing, if I use socket.io-redis module incorrectly, please tell me. :)

Setup:

      var adapter = require('socket.io-redis')({
          pubClient: pubClient,
          subClient: pubClient,
          subEvent: 'RedisPub'
      });

        const msgpack = require('msgpack-js');
        adapter.subClient.on('message', function (channel, msg) {
          const args = msgpack.decode(msg);
          if (adapter.uid != args.shift())
            logger.info({'data': args}, 'Received data from other Nodes')
        });

        adapter.subClient.on('RedisPub', function (channel, msg) {
          const args = msgpack.decode(msg);
          if (adapter.uid != args.shift())
            logger.info({'Channels.RedisPub remote message': args})
        });
        io.adapter(adapter);

Publish Message:

     _nsp.emit(data);

**Comment by darrachequesne** [comment]
Hi! AFAIK, you can't use user-defined subscription events, you have to choose among `message`, `pmessage`, ...

Please see: https://github.com/NodeRedis/node_redis#subscriber-events

**Comment by darrachequesne** [comment]
Please reopen if needed!
