### ISSUE TITLE
Callback intermittently  executing multiple times while finding the number of clients in a room

### ISSUE THREAD

**Issue by utkarshbodake** [socketio/socket.io-redis#158]
Hi,

I am intermittently getting Error “Callback was already called” when I am executing function to get the the number of clients in a room under a given namespace.
Function which is being called to find number of clients in a room is attached
[numberOfClientsInRoom.txt](https://github.com/socketio/socket.io-redis/files/623725/numberOfClientsInRoom.txt)

Also whenever the the above error comes, below traces come simultaneously:
1)
Trace
    at RedisClient.addListener (events.js:239:17)
    at Command.callback (/app/node_modules/socket.io-redis/index.js:340:17)
    at RedisClient.return_reply (/app/node_modules/socket.io-redis/node_modules/redis/index.js:689:33)
    at JavascriptReplyParser.reply_parser.send_reply (/app/node_modules/socket.io-redis/node_modules/redis/index.js:332:14)

2)
(node) warning: possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by darrachequesne** [comment]
Hi! Which version of `socket.io-redis` are you using please?

**Comment by utkarshbodake** [comment]
I am using socket.io-redis version 1.1.1

**Comment by darrachequesne** [comment]
Could you please try with `v2.0.1`? The request/response mechanism has been refactored between v1 and v2.

**Comment by utkarshbodake** [comment]
I have upgraded to v2.0.1 , but still I am facing this issue.

**Comment by darrachequesne** [comment]
@utkarshbodake any feedback?

**Comment by utkarshbodake** [comment]
@darrachequesne  I had updated it to v2.0.0 and it seems that the aforementioned error is not coming after I upgraded it.
Thanks.
