### ISSUE TITLE
How to reconnect to redis in event of error?

### ISSUE THREAD

**Issue by robinclark** [socketio/socket.io-redis#165]
In the event of an error (ECONNRESET, ECONNREFUSED, ...) I would like to attempt reconnects instead of just crashing. What would be the recommended way to go about this?

**Comment by mike-aungsan** [comment]
I have the same issue. It does not do reconnect. Any solution?

**Comment by robinclark** [comment]
You have to add a retry strategy to the pub & sub clients. If your using node_redis I think there was a retry_strategy config parameter

**Comment by mike-aungsan** [comment]
@robinclark Thanks. I got that working now. Another problem is I do not know how to send message using this module. I know how to use socketio module tho.

https://github.com/socketio/socket.io-redis/issues/193

**Comment by rhclayto** [comment]
Doesn't node_redis have a default retry_strategy that should reconnect even without declaring an explicit retry_strategy? i thought it did.
