### ISSUE TITLE
MsgPack BUFFER_SHORTAGE

### ISSUE THREAD

**Issue by pe-sean** [socketio/socket.io-redis#169]
I was looking at the socket.io-redis messages that are going across our Redis instance using the redis-cli and I am seeing packets that seem to be malformed (missing a final byte).  Can someone please help me understand this.

redis-cli
localhost:6379> psubscribe *
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "*"
3) (integer) 1
1) "pmessage"
2) "*"
3) "socket.io#/#VR6DcrGDTeFCJP2yAAAY#"
4) "\x93\xa6w9PJlb\x83\xa3nsp\xa1/\xa4data\xa6<DATA>\xa4type\x02\x82\xa5rooms\x91\xb4FOcyd8f4OtGcAjoVAADq\xa5flags\xc4"

The last item in the message is the "flags" field which says that it is of type \xc4.  If I look at the MessagePack protocol, that says that '\xc4' is for an bin8 field and it expects a least one additional byte (to say it has 0 length).

bin 8 stores a byte array whose length is up to (2^8)-1 bytes:
+--------+--------+========+
|  0xc4  |XXXXXXXX|  data  |
+--------+--------+========+

Processing the message like below produces a BUFFER_SHORTAGE error from msgpack-lite.

    out = mpl.decode(message);

message :: socket.io#/#VR6DcrGDTeFCJP2yAAAY#
.../sio-parse/node_modules/msgpack-lite/lib/flex-buffer.js:64
    if (end > this.buffer.length) throw new Error(BUFFER_SHORTAGE);

If I add a '\x00' to the message payload, I can decode it successfully.

    c = Buffer.from([0]);
    d = Buffer.concat([message, c]);
    out = mpl.decode(d);

['w9PJlb', {'nsp': '/', 'type': 2, 'data': '<DATA>'}, {'flags': <Buffer >, 'rooms': ['FOcyd8f4OtGcAjoVAADq']}]

This is different than the straight decode done in the socket.io-redis code.  I am confused by this and was hoping someone could help me.

// from socket.io-redis/index.js (140)
    var args = msgpack.decode(msg);

PS - I also have an implementation in Python that needs the same additional '\x00' in order to parse the messages that come from Redis.

**Comment by darrachequesne** [comment]
Do you know where that packet comes from?

With `io.to(<socketid>).emit('data')`, the following packet gets sent over Redis pub/sub:
```js
1) "pmessage"
2) "*"
3) "socket.io#/#VAT6-pmu-9yZ-lIWAAAA#"
4) "\x93\xa6tlD92v\x83\xa4type\x02\xa4data\x91\xa4data\xa3nsp\xa1/\x82\xa5rooms\x91\xb4VAT6-pmu-9yZ-lIWAAAA\xa5flags\xc0"
```
`\xc0` being the encoding for `undefined` ([ref](https://github.com/kawanet/msgpack-lite/blob/0.1.26/test/10.encode.js#L81))

Which version of msgpack-lite are you using?

**Comment by pe-sean** [comment]
Argh.... I forgot to check the versions of everything before starting this.  Sorry about that.

Turns out I am using socket.io-redis 1.0.0 and it uses msgpack-js 0.3.0.
Here is a nice comment from the msgpack-js website:

> Also I've added a type for undefined that works just like the null type.
> undefined  11000100  0xc4

That seems to be what I am concerned about.  I will upgrade everything and I expect that all will be well.

Its good to know that you can't mix versions because of the change in msgpack libraries.
