### ISSUE TITLE
Difference between socket.join and io.adapter.remoteJoin?

### ISSUE THREAD

**Issue by robinclark** [socketio/socket.io-redis#171]
I'm not sure I'm understanding the differences. Would someone mind clarifying?

**Comment by darrachequesne** [comment]
@robinclark `remoteJoin` allow you to make a given socket join a room from another node.

Sample use-case: https://github.com/socketio/socket.io-redis/issues/125#issue-172941004

**Comment by darrachequesne** [comment]
Do you have any suggestion to make the documentation clearer? Help is welcome!

**Comment by robinclark** [comment]
I think my socket.io knowledge was just a bit lacking. I assumed that joining rooms normally across nodes would have worked without special handling. Nice addition!

**Comment by knoxcard** [comment]
Here is a good question...do we need to run both socket.join() and socket.remoteJoin()?? or just socket.remoteJoin()?

**Comment by rodrigoreis22** [comment]
@knoxcard i have the same question, not sure if we should call both .join() and remotejoin().

**Comment by darrachequesne** [comment]
`socket.join()` is when you have access to the socket object:

```js
io.on('connect', socket => {
  socket.join('room1');
  
  socket.on('test', () => {
    socket.join('room2');
  });
});
```

`adapter.remoteJoin()` is when you don't have access to the socket object (in a multi server setup, for example):

```js
io.of('/').adapter.remoteJoin(socketId, 'room1');
```
