### ISSUE TITLE
Repeatedly subscribe same redis channel

### ISSUE THREAD

**Issue by phuongnd08** [socketio/socket.io-redis#173]
We are having multiple clients subscribe to socket.io (which in turn using socket.io-redis). I notice that socket.io-redis in turn subscribe multiple times to the same redis channel:
```
"subscribe" "socket.io#/#benchmark#"
"subscribe" "socket.io#/#benchmark#"
"subscribe" "socket.io#/#benchmark#"
"subscribe" "socket.io#/#benchmark#"
"subscribe" "socket.io#/#benchmark#"
```
I would like to think it is really unnecessary. socket.io-redis can just listen once for similar channel (but broadcast to all client if message received). Could you please give some explanation?

**Comment by darrachequesne** [comment]
That seems indeed unnecessary. https://github.com/socketio/socket.io-redis/pull/175 should fix that.
