### ISSUE TITLE
force client disconnect by socket id

### ISSUE THREAD

**Issue by overflowz** [socketio/socket.io-redis#174]
I'd like to force client disconnect by socket id using socket.io-redis. I tried a lot of research in google, but methods mentioned in old topics does not work.

Let's say, I'm making clustered application and my code at the moment runs at cluster1 instance (also I have access to all connected client's socket ids), but the client is connected to cluster2 instance. How can I force disconnect to that client by socket id only?

**Comment by darrachequesne** [comment]
As far as I know, there is currently no direct way to do that (maybe with [customRequest](https://github.com/socketio/socket.io-redis#redisadaptercustomrequestdataobject-fnfunction)).

That shouldn't be that hard to implement though, that should look a lot like [remoteJoin](https://github.com/socketio/socket.io-redis/blob/3.0.0/index.js#L641). Would you mind opening a pull request?

**Comment by overflowz** [comment]
OK, I'll try. Thanks!

**Comment by overflowz** [comment]
#177 added this feature here.
