### ISSUE TITLE
Unhandled rejection Error: timeout reached while waiting for rooms response

### ISSUE THREAD

**Issue by robinclark** [socketio/socket.io-redis#183]
I'm running a test where I have a socket join a room on a remote node. When the socket gets disconnected I would like to remove it from any rooms it was in. So whenever I get a 'disconnect' event I try to call the 'remoteLeave' for any rooms the socket was in, but I get the above error.

I'm curious whats the best way to handle this?

**Comment by darrachequesne** [comment]
Hi! Rooms are left automatically upon disconnection, so you shouldn't have to worry about that.

Reference: https://github.com/socketio/socket.io/blob/master/docs/API.md#socketleaveroom-callback

**Comment by robinclark** [comment]
Oh ok awesome I wasnt sure
