### ISSUE TITLE
setting return_buffers to true causes errors

### ISSUE THREAD

**Issue by jjb** [socketio/socket.io-redis#185]
I recently updated to the latest version (3.1.0) from 1.0.0. After doing this, exactly every other message that I emit is ignored. I bisected, and the version where this problem starts is 3.0.0. I bisected further and found that the bug was introduced in 73ce3ea81d3dca8105cb36132518166de64dbcdb. removing `return_buffers: true` from my code solved the problem.

So, maybe it's worth putting a warning in the changelog about this. I would contribute a PR but i don't know the technology well enough to word it correctly.

Thanks for a great project!

**Comment by picometer** [comment]
I had the same error and `return_buffers: true` was the problem as you posted. Thanks.

**Comment by darrachequesne** [comment]
I was unable to reproduce the issue, but I added a note [here](https://github.com/socketio/socket.io-redis/releases/tag/3.0.0), what do you think?

**Comment by jjb** [comment]
Cool

how about to History.md as well
