### ISSUE TITLE
Adapter never initializes

### ISSUE THREAD

**Issue by allthetime** [socketio/socket.io-redis#186]
I must be doing something terribly wrong, I am loading the adapter like this:

```
var app = express();
var http = require('http').Server(app);
var io = require('socket.io').listen(http);
var redis_adapter = require('socket.io-redis');
io.adapter(redis_adapter({
    host: ENV['REDIS_ADDRESS'],
    port: ENV['REDIS_PORT'],
    key: argv.redis || "0"
}));
```

Get no errors, but io.adapter never seems to be initialized and has none of the methods it's supposed to (I'm trying to use `allRooms` and `clients`), and it's not even an object, this is what I get when I log it:

```
function (v){
  if (!arguments.length) return this._adapter;
  this._adapter = v;
  for (var i in this.nsps) {
    if (this.nsps.hasOwnProperty(i)) {
      this.nsps[i].initAdapter();
    }
  }
  return this;
}
```

Which is just the adaptor initializer from the socket.io library.

Why is it not initializing?

I am on latest versions of this lib and socket.io.

**Comment by allthetime** [comment]
I found the adapter at `io.nsps['/'].adapter`, is this normal?

**Comment by darrachequesne** [comment]
Yes, this is normal. The Adapter instance is created when the `initAdapter` method is called.

If I'm not mistaken, the `Namespace#adapter` (`> io.of('/').adapter`) is the Adapter instance, whereas `Server#adapter` (`> io.adapter()`) is a method to set the Adapter class to use for every namespace.

**Comment by allthetime** [comment]
There is no mention of this in the setup/docs at all, and I for one wasted a lot of time wondering why my `io.adapater` didn't have any of the methods these docs said it would. This is the first code snippet we see:
```
io.adapter.clients(function (err, clients) {
  console.log(clients); // an array containing all connected socket ids
});
```

**Comment by mike-aungsan** [comment]
OMG. I already spend 2 hours plus. @allthetime  how do we call this function? io.adapter.clients
Many Thanks

**Comment by mike-aungsan** [comment]
Thanks
