### ISSUE TITLE
How to send messages to especific room across nodes

### ISSUE THREAD

**Issue by venomlust** [socketio/socket.io-redis#188]
I saw there's a method called "clients" where it returns array of strings <clients ids>, but I dont see any "emit" or "in" methods. I need to send messages to a especific room across all nodes. 

Any ideias how I can achive that?

**Comment by darrachequesne** [comment]
If you use the Redis Adapter, any message is broadcast accross all nodes by default.

**Comment by venomlust** [comment]
```
const redisAdapter = require('socket.io-redis');
io.adapter(redisAdapter({
  host:'127.0.0.1',
  port:6379
}));`
```

and then

`io.to('some room').emit('some event'):`

should work?

**Comment by darrachequesne** [comment]
Exactly :+1:
