### ISSUE TITLE
Persisting room when server shuts down/crashes

### ISSUE THREAD

**Issue by rhclayto** [socketio/socket.io-redis#203]
This is a question, not a bug report.

I am developing a socket.io application to be hosted on Amazon Web Services EC2 instances behind an Application Load Balancer. It will use auto-scaling, so instances will be brought up & torn down dynamically.

With this adapter, I am able to have clients connected on one machine join rooms on another machine. However, in this scenario, what happens when the pool of servers is auto-scaled down, & the machine the room exists on is terminated? Does the room cease to exist? Will I need to implement logic in the application to deal with this? Dynamically creating rooms on different servers when one is about to auto-scale down. Or for that matter, what happens to rooms when the server they are on crashes?

**Comment by lkp0907** [comment]
How About `Pause` Your Ec2 and checking XD

**Comment by darrachequesne** [comment]
@rhclayto when the server is closed, the rooms stored in the adapter (and the sockets themselves) are indeed deleted.

When the client reconnect on another server, you'll need some logic to recreate those associations.

**Comment by rhclayto** [comment]
@darrachequesne I kind of thought as much but wanted to make sure the adapter didn't have something internally that might accomplish the same thing before doing it myself. Thanks for your response.
