### ISSUE TITLE
TypeError: Cannot read property 'encode' of undefined

### ISSUE THREAD

**Issue by marcosc90** [socketio/socket.io-redis#222]
When using **socket.io-redis@5.0.1** I get the following error:

```
TypeError: Cannot read property 'encode' of undefined
    at Redis.Adapter.broadcast (/var/www/test/node_modules/socket.io-redis/node_modules/socket.io-adapter/index.js:136:15)
    at Redis.broadcast (/var/www/test/node_modules/socket.io-redis/index.js:414:33)
    at Namespace.emit (/var/www/test/node_modules/socket.io/lib/namespace.js:222:18)
    at EventEmitter.emitter.on.data (/var/www/test/private/test.js:121:16)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at Test.handleResponse (/var/www/test/private/test.js:286:17)
    at EventRequest.request.on (/var/www/test/private/test.js:198:9)
    at emitOne (events.js:96:13)
    at EventRequest.emit (events.js:191:7)
```

**My code:**
```javascript
const socketio = require('socket.io');
const express = require('express');

const app = express();
const server = require('http').Server(app);

const io = socketio(server);
const redis = require('socket.io-redis');

server.listen(3002);

io.adapter(redis({ host: 'localhost', port: 6379 }));
io.on('connection', (socket) =>{
	const room = 'test';

	socket.join(room);

	socket.on('chat message', () => {
		console.log("message");
		io.to(room).emit('chat message', 'hi');  //This is where the error starts.
	});
});
```

I fixed it changing this line:

`this.encoder = nsp.server.encoder;`

with:

`this.encoder = nsp.adapter.encoder;`

in `socket.io-redis/node_modules/socket.io-adapter/index.js`

But I really don't think I should be doing that.

**Info:**

**OS:** Ubuntu 16.04 64-bit

├─┬ socket.io@1.7.3
│ └── socket.io-adapter@0.5.0 
└─┬ socket.io-redis@5.0.1
  └── socket.io-adapter@1.1.0

**Comment by johnfrades** [comment]
I'm having the same issue

**Comment by darrachequesne** [comment]
As noted in the [release note](https://github.com/socketio/socket.io-redis/releases/tag/5.0.0), `socket.io-redis@5.0.1` is not compatible with `socket.io@1.x`.

Related: https://github.com/socketio/socket.io-adapter/pull/47

**Comment by marcosc90** [comment]
@darrachequesne Thanks, my bad for not reading the release notes. 
In any case I would recommend showing a warning if socket.io version is lower than 2.

**Comment by olegmdev** [comment]
I have this issue with `socket.io@2.0.1`. 

@marcosc90 's solution helped, but it's not acceptable to make such changes

**Comment by darrachequesne** [comment]
> but it's not acceptable to make such changes

May I ask what you do mean?

**Comment by olegmdev** [comment]
I meant to make changes inside dependent node_modules sources, nevermind.

Rolling back to `socket.io-redis@5.0.0` (from 5.0.1) did the trick.

**Comment by felipemarques** [comment]
Iam rolling back to socket.io-redis@5.0.0 likve @olegmdev mentioned, but not work

**Comment by felipemarques** [comment]
`{
  "name": "newpubsub",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "NODE_ENV=production node ./bin/www",
    "start:dev": "NODE_ENV=development node ./bin/www"
  },
  "dependencies": {
    "bcrypt": "^1.0.3",
    "body-parser": "~1.14.1",
    "connect-redis": "^3.0.0",
    "cookie-parser": "~1.4.0",
    "debug": "~2.2.0",
    "ejs": "~2.3.1",
    "express": "~4.13.3",
    "express-session": "^1.11.1",
    "express-useragent": "^1.0.8",
    "faker": "^4.1.0",
    "hiredis": "^0.4.1",
    "lodash": "^4.17.4",
    "md5": "^2.2.1",
    "moment": "^2.17.1",
    "morgan": "~1.6.1",
    "mysql": "mysqljs/mysql",
    "redis": "^2.1.0",
    "request": "^2.81.0",
    "serve-favicon": "~2.3.0",
    "session.socket.io": "^0.2.0",
    "socket.io": "^1.3.5",
    "socket.io-emitter": "^3.1.1",
    "socket.io-express-session": "^0.1.3",
    "socket.io-redis": "5.0.0",
    "sticky-session": "^1.0.1",
    "uniqid": "^4.1.1"
  },
  "devDependencies": {
    "socket-stress-test": "^0.1.0",
    "socket.io-client": "^2.0.3"
  }
}
`

**Comment by felipemarques** [comment]
Worked only when i update socket.io to 2.x

**Comment by darrachequesne** [comment]
@felipemarques please see https://github.com/socketio/socket.io-redis/releases/tag/5.0.0.

**Comment by jonathan-casarrubias** [comment]
I'm having this problem, I'm using socket.io 2.1.1 and socket.io-redis 5.2.0

**Comment by danieldunderfelt** [comment]
I used patch-package to make the change @marcosc90 suggested, and it works. Is this a bug? Can it be fixed?

I'm working on a legacy Sails 0.12 app and it is not feasible to upgrade at this time so this is the solution I will have to go with.
