### ISSUE TITLE
Error: Integer is unsafe

### ISSUE THREAD

**Issue by lakamsani** [socketio/socket.io-redis#223]
Hi, trying socket.io-redis 5.0.1 with our app triggered this error when 
calling `io.sockets.in("someChannel").emit('playerEnter', "1234",jsonObject);` where `jsonObject` is some app specific object (player in this case)

```bash

3|onkore   | Error: Integer is unsafe
3|onkore   |     at _encode (/home/ec2-user/onkore-node/node_modules/notepack.io/lib/encode.js:106:13)
3|onkore   |     at _encode (/home/ec2-user/onkore-node/node_modules/notepack.io/lib/encode.js:261:15)
3|onkore   |     at _encode (/home/ec2-user/onkore-node/node_modules/notepack.io/lib/encode.js:191:17)
3|onkore   |     at _encode (/home/ec2-user/onkore-node/node_modules/notepack.io/lib/encode.js:261:15)
3|onkore   |     at _encode (/home/ec2-user/onkore-node/node_modules/notepack.io/lib/encode.js:191:17)
3|onkore   |     at Object.encode (/home/ec2-user/onkore-node/node_modules/notepack.io/lib/encode.js:281:14)
3|onkore   |     at Redis.broadcast (/home/ec2-user/onkore-node/node_modules/socket.io-redis/index.js:406:25)
3|onkore   |     at Namespace.emit (/home/ec2-user/onkore-node/node_modules/socket.io/lib/namespace.js:218:18)
```

line 106 of `notepack.io/lib/encode.js:106:` looks like this

```javascript
    if (Math.abs(value) > MAX_SAFE_INTEGER) {
       throw new Error('Integer is unsafe');
     }
```

npm ls socket.io-redis shows:
````
└─┬ socket.io-redis@5.0.1
  └── notepack.io@1.0.1
````

What is the next place to look? Is this because our payload has some out of range integer? This code works with `socket.io-redis@4.0.0` which does not appear to be dependent on `notepack.io`

**Comment by darrachequesne** [comment]
Hi @lakamsani! Any particular reason you would be using integers bigger than 2^53?

I think previous versions (based on `msgpack-lite`) just silently truncated those numbers.

**Comment by lakamsani** [comment]
@darrachequesne  unless there is some bug in our code we are not intentionally using integers larger than 2^53. I will turn on more debugging in my app. If there are any socket.io-redis debug flags that might help get more data let us know. We have a two different environments dev and test. It works fine in dev environment but running into this problem in test environment. Needs to work there before we can release to production.

**Comment by lakamsani** [comment]
We found a field with a value  9.007199254740991e+36 in that was causing this crash. We can close this and we will debug further in our app.

**Comment by darrachequesne** [comment]
@lakamsani great, thanks for the follow-up!

**Comment by whoisstan** [comment]
hi, same issue, I am creating a channel name like 'user:${user.uuid}' and am simply calling

io.sockets.in(user.getChannel()).emit(property.getSafe());

am I understanding right that I need to be careful with the length of the room name? is this part of a spec? it was a tough error to track down since it didn't happen all the time.

is there a safe string length so this error will never happen?

thanks much,
stan

**Comment by whoisstan** [comment]
I created an issue here, not sure if it's just related to socket.io-redis or socket.io in general
https://github.com/socketio/socket.io/issues/3035

thanks

**Comment by darrachequesne** [comment]
@whoisstan that should be fixed by https://github.com/darrachequesne/notepack/pull/15 and https://github.com/socketio/socket.io-redis/pull/242.
