### ISSUE TITLE
Memory leak in Redis.requests

### ISSUE THREAD

**Issue by beaucollins** [socketio/socket.io-redis#224]
I'm experiencing memory leaks in a long running server process that I've tracked down to `socket.io-redis`.

In `Redis.prototype.onresponse` it fails to delete any requests from `Redis.requests` which causes the `Redis.requests` object to grow unbounded.

For example, in `onresponse` for a `requestTypes.clients` it eventually hits [this line](https://github.com/socketio/socket.io-redis/blob/c743d613107fd95fb1d2b72f69e9760ab0678bff/index.js#L342):

```js
if (request.msgCount === request.numsub) {
  clearTimeout(request.timeout);
  if (request.callback) process.nextTick(request.callback.bind(null, null, Object.keys(request.clients)));
  delete self.requests[request.requestid]; // Attempts to remove the request object record
}
```

I set up a breakpoint on that line and `request.requestid` is `null`. Here's a screen cap of inspecting the `request` object when execution is paused at line 342:

<img width="368" alt="screen shot 2017-06-03 at 3 43 58 pm" src="https://cloud.githubusercontent.com/assets/19795/26757526/9005ac46-4873-11e7-810e-7a57a6a4e2fd.png">

Note that there is no `requestid` property on the `request` object.

**Comment by beaucollins** [comment]
@darrachequesne I've been running my fork on my production server and the memory leak is gone since deploying it.

<img width="728" alt="screen shot 2017-06-04 at 1 48 20 am" src="https://cloud.githubusercontent.com/assets/19795/26760233/fa6a097a-48c7-11e7-8094-e704ee5ff879.png">

**Comment by artofspeed** [comment]
@beaucollins thanks, may i know which tool u used to track memory usage over time, is that pm2?

**Comment by beaucollins** [comment]
@artofspeed That is a Grafana dashboard. I'm not sure what the datasource of that graph is. I believe InfluxDB.

To debug the issue I used [node-inspector](https://github.com/node-inspector/node-inspector/)
