### ISSUE TITLE
Total Connections

### ISSUE THREAD

**Issue by swapnil001** [socketio/socket.io-redis#229]
I have 500 clients connected to redis. They are connected on 3 different ec2 instances. Now to broadcast my event, how many connections socket.io-redis makes to redis?

Is it 500 * 500 ? (1 connection/connected client)

Reason for asking, I have only 317 connected client to my redis. But total number of connection is more than 40,000. How is that possible? My nodejs server timeout is set to 0. And I am not closing redis connection in my app.

**Comment by darrachequesne** [comment]
@swapnil001 each socket.io-redis instance opens two Redis connections (one for publishing and one for subscribing).

Could you please provide some code reproducing the issue?

**Comment by swapnil001** [comment]
var server = http.createServer(app);
var io = require('socket.io').listen(server);
io.set('transports', ['websocket']);
var socketRedis = require('socket.io-redis');
io.adapter(socketRedis({ host: 'xxxxx.MYHOST_URL.xxx', port: 6379 }));
var redisClient = require('redis').createClient;
var redis = redisClient(6379, 'xxxxx.MYHOST_URL.xxx', port: 6379 }));
var redisClient = require('redis').createClient;');

var matchcenter = require('./routes/matchcenter')(app, redis, io);

Now when I look at redis stat - 

keys       mem      clients blocked requests            connections          
3372       560.45M  306     0       7269064 (+0)        22885

I am getting above result. Ideally each node process should create one connection and I have 24 nodejs process running in cluster mode.

When there are concurrent request on my process, redis response is increasing from 10ms to 3 seconds. So I am looking for possible causes.

**Comment by swapnil001** [comment]
When there is an event, socket emits a message. All connected clients then make an API Call to update there leaderboard. When this process happens, redis timeout increases.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
