### ISSUE TITLE
Correct configuration of Socket.io-redis with Redis Cluster

### ISSUE THREAD

**Issue by pinkladywithcoco** [socketio/socket.io-redis#230]
Hi there

Could you please confirm whether this is the correct way to use Redis Cluster:

```
var io = require('socket.io')(server);
var Redis = require("ioredis");
var adapter = require('socket.io-redis');

var cluster = new Redis.Cluster([{
  port: 6380,
  host: '127.0.0.1'
}, {
  port: 6381,
  host: '127.0.0.1'
}]);


io.adapter(adapter({ pubClient: cluster, subClient: cluster, subEvent: 'messageBuffer' }));
```
Is is the correct? if not please show me how to understand.

This will allow the servers to broadcast and emit events to and from each other?

Thank you very much for your time

**Comment by darrachequesne** [comment]
`io.adapter(adapter({ pubClient: cluster, subClient: cluster }));` should be sufficient.

**Comment by darrachequesne** [comment]
The example was added in the [README](https://github.com/socketio/socket.io-redis#with-ioredis-client).
