### ISSUE TITLE
socket.broadcast in socket.io-adapter 'TypeError: Cannot read property \'encode\' of undefined'

### ISSUE THREAD

**Issue by RAdevelop** [socketio/socket.io-redis#232]
Hi!
Node v6.1.0
socket.io 1.7.3
socket.io-redis 5.1.0

error in 
node_modules/socket.io-redis/node_modules/socket.io-adapter/index.js:25
nsp.server.encoder is undefined

then try
index.js

```
const SioRedis = require('socket.io-redis');
io
	.adapter(SioRedis({ 
		host: AppConfig.redis.host, port: AppConfig.redis.port
		, pubClient: IORedis(readerRedisOts)
		, subClient: IORedis(writerRedisOpts)
	}))
	.origins('*:*', opts).of('/'+chanel, (socket)=>
	{
		console.log('----------------');
		console.log('on connect! socket.id = ', socket.id);
	})
	.on('error', (err)=>
	{
		console.log('io on error');
		Logger.error(err);
	})
	.on('connect', onConnect)
	;

function onConnect(socket)
	{
		Logger.info('onConnect');
		// sending to the client
		//socket.emit('message', 'can you hear me?', 1, 2, 'abc');
		
		// sending to all clients except sender
		socket.broadcast.emit('broadcast', 'hello friends!');
	}
```

> [ 'TypeError: Cannot read property \'encode\' of undefined',
     '    at Redis.Adapter.broadcast (/Users/ra/MyDevelopment/web/mcjs2/node_modules/socket.io-redis/node_modules/socket.io-adapter/index.js:137:15)',
     '    at Redis.broadcast (/Users/ra/MyDevelopment/web/mcjs2/node_modules/socket.io-redis/index.js:416:33)',
     '    at Socket.emit (/Users/ra/MyDevelopment/web/mcjs2/node_modules/socket.io/lib/socket.js:161:20)',
     '    at Namespace.onConnect (/Users/ra/MyDevelopment/web/mcjs2/app/lib/chat/index.js:80:20)',
     '    at emitOne (events.js:101:20)',
     '    at Namespace.emit (events.js:188:7)',
     '    at Namespace.emit (/Users/ra/MyDevelopment/web/mcjs2/node_modules/socket.io/lib/namespace.js:209:10)',
     '    at /Users/ra/MyDevelopment/web/mcjs2/node_modules/socket.io/lib/namespace.js:176:14',
     '    at _combinedTickCallback (internal/process/next_tick.js:67:7)',
     '    at process._tickCallback (internal/process/next_tick.js:98:9)' ] }

**Comment by darrachequesne** [comment]
Duplicate of #222, please see https://github.com/socketio/socket.io-redis/issues/222#issuecomment-301379404

**Comment by RAdevelop** [comment]
@darrachequesne thanks!
i did'n find it earlier.

problem is solved after uninstall socket.io 1.7.3 and install 2.0.3 (latest for now).
