### ISSUE TITLE
Error Cannot read property 'encode' of undefined

### ISSUE THREAD

**Issue by natalio** [socketio/socket.io-redis#234]
I put "io.adapter (redis ())" and I have an "Cannot read property 'encode' of undefined" exception when I make "socket.broadcast"

**Comment by ArthurNC** [comment]
Could be a compatibility issue. Try updating both socket.io and socket.io-redis to the latest versions.

**Comment by davidlanger** [comment]
@ArthurNC yes that was caused this error for me. Updated to latest version to fix.

**Comment by xiaowuwuwuwuwu** [comment]
@davidlanger What version of socket.io and socket.io-redis are you using?

**Comment by davidlanger** [comment]
@xiaowuwuwuwuwu Now I am using: 

    "socket.io": "^2.0.3",
    "socket.io-redis": "^5.1.0",

before I used socket.io 1.x

**Comment by natalio** [comment]
@davidlanger i´m test socket.broadcast.emit("test","test") but not work

**Comment by davidlanger** [comment]
@natalio which versions of socket.io and socket.io-redis are you using?

**Comment by darrachequesne** [comment]
Please refer to @davidlanger answer [[^]](https://github.com/socketio/socket.io-redis/issues/234#issuecomment-318050999).

I updated the release note to make it clearer: https://github.com/socketio/socket.io-redis/releases/tag/5.0.0

**Comment by natalio** [comment]
@davidlanger  "socket.io": "2.0.3", "socket.io-emitter": "3.0.1",

**Comment by davidlanger** [comment]
what has socket.io-emitter to do with that? Perhaps the error lies here? Try without using socket.io-emitter

**Comment by natalio** [comment]
@davidlanger sorry i messed I'm not using socket.io-emitter 
im using "socket.io": "2.0.3", "socket.io-redis": "^5.1.0"

**Comment by natalio** [comment]
example:
when set io.adapter(redis()); 
socket.broadcast.emit("test","test") but not work in my code

**Comment by natalio** [comment]
@davidlanger I saw that not only did I have this problem
https://github.com/socketio/socket.io-redis/issues/237

**Comment by davidlanger** [comment]
@natalio yepp seems like that is another problem. I don't use `broadcast`
