### ISSUE TITLE
socket.broadcast.to not working

### ISSUE THREAD

**Issue by ArthurNC** [socketio/socket.io-redis#237]
`socket.broadcast.to[socket.id]` does not appear to be working. Using two separate servers on different ports, broadcasting messages across servers with `socket.broadcast.to[socket.id].emit(messageName, message) ` does not appear to work.

Redis server is running on port 6379 and the redis-cli monitor indicates messages are being published, but not received:
<img width="489" alt="screen shot 2017-07-21 at 7 25 18 pm" src="https://user-images.githubusercontent.com/28462424/28538359-441455ce-706b-11e7-9305-017fe3e2533e.png">

```
const client = require('redis').createClient()
const io = require('socket.io')(server)
const redis = require('socket.io-redis')
io.adapter(redis({ host: 'localhost', port: 6379 }))

io.on('connection', function(socket) {
       //not received by client
       socket.broadcast.to(socketID).emit('personalMessage-server', message)
})
```

**Comment by soulomoon** [comment]
same here

**Comment by darrachequesne** [comment]
In your example, where does `socketID` come from?

Ref: https://github.com/socketio/socket.io/blob/master/docs/emit.md

**Comment by natalio** [comment]
example:
when set io.adapter(redis());
socket.broadcast.emit("test","test") but not work in my code

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
