### ISSUE TITLE
Why isn't `socket.join` related to `adapter.remoteJoin`? 

### ISSUE THREAD

**Issue by mrik974** [socketio/socket.io-redis#241]
Hi! 

This is more a question than an issue. I have found the related issues in the list, but the question remains.
Is there a use case where a socket only needs to join a room on a single node ?
Or is it because the method `adapter.addAll` didn't exist before ?

**Comment by darrachequesne** [comment]
It's because a given socket only exists on a single node, and its rooms are stored at the node level (not shared across the cluster).

The `remoteJoin` method was added later, so that you can make a random socket join a room given its id, even if you don't have access to the object.

**Comment by cinout** [comment]
Hi @darrachequesne . How does a socket know where the `room` located? I mean `adapter.remoteJoin()` is used for joining a room on a remote node, while `socket.join()` is used for joining a room on local node. Is there any api for a socket to know about where the `room` is located (local or remote)?
