### ISSUE TITLE
io.of.adapter.remoteDisconnect not working

### ISSUE THREAD

**Issue by kishe89** [socketio/socket.io-redis#245]
i called it in
`socket.on('disconnect', function () {
            if (addedUser) {
                --numUsers;
                io.of('/').adapter.remoteDisconnect(socket.id,true,err=>{
                    if(err){console.log(err);}
                    // echo globally that this client has left
                    socket.broadcast.emit('user left', {
                        username: socket.username,
                        numUsers: numUsers
                    });
                });
            }
        });`

But this does not work.
The error message is [ERROR: timeout waiting for remoteDisconnect response].
Why did this happen?
I think this function needs a specific socket ID. is not it?
please help me

**Comment by kishe89** [comment]
may be this function is internal function
socket disconnect At the time of the event, the socket has already disappeared from the adapter.

**Comment by knoxcard** [comment]
Try socket.on('disconnecting'), socket.on('disconnect') is too late...
```
socket.on('disconnecting', () => {
      websocket.of('/').adapter.remoteDisconnect(sess.id, true, err => {
        delete socket.rooms[sess.id]
        socket.removeAllListeners()
      })
})
```

**Comment by kishe89** [comment]
Thanks to reply

**Comment by knoxcard** [comment]
Close ticket?
