### ISSUE TITLE
index.js syntax error

### ISSUE THREAD

**Issue by kishe89** [socketio/socket.io-redis#246]
`sub.psubscribe(this.channel + '*', function(err){
      if (err) self.emit('error', err);
    });`

It is the 105th line in index.js.
psubscribe is not function.

**Comment by KristjanTammekivi** [comment]
psubscribe is a function on both ioredis and node-redis, and changing it to subscribe would break everything, since subscribe doesn't subscribe to a pattern. (see https://redis.io/commands/psubscribe vs https://redis.io/commands/subscribe)
