### ISSUE TITLE
Question : can we store other data than "id" and "room" ?

### ISSUE THREAD

**Issue by MatthieuHPP** [socketio/socket.io-redis#249]
Hello,

I am working on an application requiring the share of other data than "id" and "rooms" among all peers of the rooms : pseudo, profil.... I do not want that each peer already in the room send its data to new peers entering the room that will already broadcast its arrival to all peers...

I could use a supplementary database (I am familiar with Mongo) to do so but I would like to be sure there is no way to do this with socket.io-redis :
Is there a way to associate data to a room with socket.io-redis ?

Many thanks 

Matthieu

**Comment by darrachequesne** [comment]
Since `socket.io-redis` already depends on Redis, you should be able to use it to store your data. Please see https://redis.io/

**Comment by MatthieuHPP** [comment]
Many thanks Damien
