### ISSUE TITLE
Unable to get list of clients in a given room

### ISSUE THREAD

**Issue by reks-scripts** [socketio/socket.io-redis#251]
Hi guys.  I need some help here.  Not sure what I'm doing wrong.  We have 100s of clients using socket.io which all connect to our node app on the server.  Currently we're only running one instance but I've been tasked with adding support for scaling out.

So I have the adapter in place, creating a pub and sub client, connecting to redis etc.  Our dev server is scaled out to 2 instances and I can connect two different clients (one to each server) have them join the same room and broadcast to each other perfectly.

The admin side of our app is laid out as a dashboard that makes it easy for admins to see which clients are connected, how many connections each client has etc.  To do this, I have end points in place that return a list of connected clients by room name.   After scaling out the dev server, these end points are (as expected) only returning clients that are currently connected to the room on the same server.  So I set out to update the end points with the new functions provided by socket.io-redis.  So far I've tried: 

io.of('/').adapter.clients(['room1'], (err, clients) => {
  console.log(clients);
});

and

io.in('room1').clients((err, clients) => {
  console.log(clients);
});

In both cases, I get back an empty object.  It doesn't even list the clients that are connected on the same server let alone all the clients across all servers.

I feel like I must be missing something obvious somewhere.

**Comment by shellka** [comment]
Yup, i need the same.
In 4.x version we've used 
`emitter.redis.pubsub(["NUMSUB", namespaceWithPlayer + name + '#'], function (err, reply) {
                callback(err, (reply && typeof reply[1] !== 'undefined') ? reply[1] : null);
            });`
but now socket.io has only 2 channels in the redis, so it doesn't work anymore.

**Comment by reks-scripts** [comment]
OK so I finally got adapter.clients working and it's returning me a list of socket IDs which is great but if I have an ID for a socket that lives on another server/process, it doesn't really do me much good.  I really need to be able to access the socket objects.  

I'm really trying to avoid storing associations between socket IDs and client config data since socket.io manages all that already by allowing us to store client config data on the socket.

**Comment by reks-scripts** [comment]
We finally resolved this issue.  It ended up being an issue with the initial setup of socket.io and the adapter.  Here's what we did in case it helps anyone else:

`var express = require('express');
var socketio = require('socket.io');
var redis = require('redis');
var adapter = require('socket.io-redis');

var app = express();

const io_s = socketio('', {
    'transports': ['websocket'],
    'path': '/socket.io'
});

const pub = redis.createClient(app.locals.redisPort, app.locals.redisHost);
pub.auth(app.locals.redisKey);

const sub = redis.createClient(app.locals.redisPort, app.locals.redisHost);
sub.auth(app.locals.redisKey);

io_s.adapter(adapter({key: app.locals.appName + app.locals.slot, pubClient: pub, subClient: sub }));

const io = io_s.sockets;
app.set('io', io_s);

io.adapter.customHook = function (data, callback) {
    if (data && data.request === "getSockets") { 
        var rooms= {};

        for (var room in io.adapter.rooms) {
            if (io.adapter.rooms.hasOwnProperty(room)) {
                // socket.io adds a bunch of extra rooms, filter here for the ones we care about
                if (room.match(/^[0-9]{4}$/g)) {
                    rooms[room] = {};
                    rooms[room].sockets = [];

                    var sockets = io.adapter.rooms[room].sockets;

                    for (var socket in sockets) {
                        if (sockets.hasOwnProperty(socket)) {
                            if (io.connected[socket]) {
                                rooms[room].sockets.push(io.connected[socket]);
                            }
                        }
                    }
                }
            }
        }
        callback(null, rooms);
    } else if (data && data.request === "getSocketsByRoomId") {
        var roomId = data.roomId;
        rooms = {};

        if (io.adapter.rooms[clubId]) {
            rooms[roomId] = {};
            rooms[roomId].sockets = [];

            var sockets = io.adapter.rooms[roomId].sockets;

            for (socket in sockets) {
                if (sockets.hasOwnProperty(socket)) {
                    if (io.connected[socket]) {
                        rooms[roomId].sockets.push(io.connected[socket]);
                    }
                }
            }
        }
        callback(clubs);   
    } else {
        callback(null, null);
    }
}`

From there we just had to write a function that would call the custom hook and return the socket connections:

`// get info on all connected sockets (roomId optional)
function getSockets(roomId, callback) {

    if (!callback || typeof callback !== "function") {
        return;
    }

    // use custom hook to make request to get all sockets for a room
    var requestData = {};
    if (roomId) {
        requestData.request = "getSocketsByRoom";
        requestData.roomId = roomId;
    } else {
        requestData.request = "getSockets";
    }

    io.adapter.customRequest(requestData, function (err, data) {
        if (err) {
            callback(err);
        } else {
            // data is an array of responses from each instance of the app
            callback(null, data);
        }
    });
}`
