### ISSUE TITLE
How can i emit event to all servers?

### ISSUE THREAD

**Issue by nschurmann** [socketio/socket.io-redis#255]
The code in the readme seems to be incomplete, there ain't a minimal example where more than one instance can be connected

**Comment by LeenaBhegade** [comment]
@nschurmann did you manage to connect more than one instance of server ?

**Comment by nschurmann** [comment]
@LeenaBhegade yes, we created 2 clients, a pub and a sub in every machine (we deploy using amazon ECS), a redis server in elastic cache, now when we emit a message every machine receives it.

You can try this with 2 computers and one having a redis server while the other 2 have the code base.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
