### ISSUE TITLE
How to get socket object by socket.id

### ISSUE THREAD

**Issue by SunGg12138** [socketio/socket.io-redis#257]
How to get socket object by socket.id

**Comment by rohanrhu** [comment]
You can't do it. Socket object is a JavaScript object in its process. Socket.io-redis is for IPC between different processes with messaging. The socket that you want retrieve by id maybe in another process.

**Comment by HsinHeng** [comment]
if you used multiple nodes architecture, the connected socket object was "only" existed in connected node scope. You may get "undefined" if your wanted socket is not in local instance scope.

therefore, if you really want some "attributes" of socket object you can use...

solutions: customHook, customRequest,

You can use customRequest to communicate with other node instance and retrieve some attributes of "socket object" by specific socketId.

hook the function on your application, and use customRequest to get you wanted.

**Comment by knoxcard** [comment]
close ticket?

**Comment by darrachequesne** [comment]
Let's continue the discussion here: https://github.com/socketio/socket.io-redis/issues/357#issuecomment-703323613
