### ISSUE TITLE
Does the adapter need to be called with new?

### ISSUE THREAD

**Issue by robtraynor** [socketio/socket.io-redis#260]
I was trying to add a customHook to my app, and ran into the issue of `io.of('/').adapter.customRequest` not being a function, after some sleuthing I found that it would need to be called with 'new' for it to work i.e. changing what is in the documentation from

`io.adapter(redis({ host: 'localhost', port: 6379 }));`

to

`io.adapter(new redis({ host: 'localhost', port: 6379 }));`

Is this correct (should the documentation be updated) or am I doing something wrong?

**Comment by DingGGu** [comment]
Give a information for what did you use redis client.

Otherwise, You just use like following codes:
```javascript
const adapter = require('socket.io-redis')
const Adapter = adapter({host: config.redis.host, port: config.redis.port}
```
Initialize Adapter

and attach to socket.io
```javascript
const io = require('socket.io')({
  transports: ['websocket'],
  adapter: Adapter
})
```

**Comment by darrachequesne** [comment]
`io.adapter(redis({ host: 'localhost', port: 6379 }));` must indeed be called before using `io.of('/').adapter.customRequest` (but I guess you already found a solution).
