### ISSUE TITLE
what's stored in redis db?

### ISSUE THREAD

**Issue by yongdi** [socketio/socket.io-redis#261]
I had successfully run a redis-socketio, but see nothing in redis. what objects are them and how could I check?
  
furthermore, is it safe for me to give a running redis server with other data to it to be the role?

**Comment by DingGGu** [comment]
socket.io-redis use [Redis pub/sub](https://redis.io/topics/pubsub).
Pub/Sub is a message communication between each nodes. (e.g. multi-threads, multi-instances)

You can see following command:
```
$ redis-cli
```
Connect to redis server.

Just type a word `monitor` - https://redis.io/commands/monitor
then start a conversations.

You can see messages between each nodes.
