### ISSUE TITLE
redundant namespace in debug logs

### ISSUE THREAD

**Issue by umairda** [socketio/socket.io-redis#266]
I was debugging my project and was trying to determine whether to pass `socket.id` or `socket.conn.id` in order to join the default room that each socket is placed in. I modified the `debug` statements in the `broadcast` function so I could better understand what was going on. I made the following changes (added one debug statement, modified another debug statement): 
```
  Redis.prototype.broadcast = function(packet, opts, remote){
    packet.nsp = this.nsp.name;
    if (!(remote || (opts && opts.flags && opts.flags.local))) {
      var msg = msgpack.encode([uid, packet, opts]);
      var channel = this.channel;
      debug('[ broadcast ] - opts: %O',opts)
      if (opts.rooms && opts.rooms.length === 1) {
        channel += opts.rooms[0] + '#';
      }
      debug('publishing message to channel %s %O %O', channel, packet, opts);
      pub.publish(channel, msg);
    }
    Adapter.prototype.broadcast.call(this, packet, opts);
  };
```
I learned that `socket.id` is the correct room to join (default room) however when I do this the second debug statement displays the namespace in the channel twice.

That is when using namespaces, `socket.id` is `/namespace#some-socket-id` and the channel will be `/namespace#/namespace#some-socket-id`

Despite the namespace redundancy in the `channel` variable everything seems to work fine. 

It makes sense that the namespace will be duplicated because 
 - `opts.rooms[0]` will be `/namespace#some-socket-id`
 - `nsp.name` will be `/namespace`
 - and `channel` is set in the constructor:  `this.channel = prefix + '#' + nsp.name + '#';`

---

Again as far as I can tell this isn't causing an issue but I thought I would point this out in case there is something I have overlooked (and there really is an issue)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
