### ISSUE TITLE
 The "pubsub numsub" is invalid at redis cluster.  Support redis cluster?

### ISSUE THREAD

**Issue by SunGg12138** [socketio/socket.io-redis#267]
"pubsub numsub channel", it only returns results pertaining to the server you're directly connected to.
[https://github.com/antirez/redis/issues/1137](https://github.com/antirez/redis/issues/1137)

**Comment by darrachequesne** [comment]
I think we could maybe use the return value of the [publish](https://redis.io/commands/publish) method, instead of the pubsub count.

I won't have much time to dedicate to that matter currently, would you have time to submit a PR?

**Comment by darrachequesne** [comment]
Well, actually, it seems the return value of the publish is also the number of subscribers of the current node.

```
$ redis-cli -c -p 7000
127.0.0.1:7000> PSUBSCRIBE *
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "*"
3) (integer) 1
1) "pmessage"
2) "*"
3) "hey"
4) "you"

$ redis-cli -c -p 7001
127.0.0.1:7001> PSUBSCRIBE *
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "*"
3) (integer) 1
1) "pmessage"
2) "*"
3) "hey"
4) "you"

$ redis-cli -c -p 7002
127.0.0.1:7002> PUBLISH hey you
(integer) 0
$ redis-cli -c -p 7001
127.0.0.1:7001> PUBLISH hey you
(integer) 1
```

Also:
```
$ redis-cli -c -p 7000
127.0.0.1:7000> SUBSCRIBE custom
Reading messages... (press Ctrl-C to quit)
1) "subscribe"
2) "custom"
3) (integer) 1

$ redis-cli -c -p 7001
127.0.0.1:7001> PUBSUB CHANNELS
(empty list or set)
$ redis-cli -c -p 7000
127.0.0.1:7000> PUBSUB CHANNELS
1) "custom"
```

We might have to add a ping/pong mechanism for this to work with a redis cluster.
