### ISSUE TITLE
Help - Cannot broadcast messages between two socket.IO connections 

### ISSUE THREAD

**Issue by LeenaBhegade** [socketio/socket.io-redis#269]
Hello,

I am using Socket.io in my Node.js app and I will be having multiple instances of my app running in future. I will need multiple Socket.IO nodes to accept connections from each other. I am using socket.io-redis. But I am not able to broadcast messages between these socket.io connections. Below is the code snippet.

**app.js**
```
var socketio = require('socket.io')(server, {
  serveClient: config.env !== 'production',
  path: '/socket.io-client'
});

const adapter = redis({ host: 'localhost', port: 6379 });

adapter.pubClient.on('error', function(){
logger.error('Error on pub client');
});

adapter.subClient.on('error', function(){
logger.error('Error on sub client');
});

socketio.adapter(adapter);

require('./config/socketio').default(socketio);
```
**socketio.js**
```
socketio.on('connection', function(socket) {
    socket.address = `${socket.request.connection.remoteAddress}:${socket.request.connection.remotePort}`;

    socket.connectedAt = new Date();

    socket.log = function(...data) {
      console.log(`SocketIO ${socket.nsp.name} [${socket.address}]`, ...data);
    };

    // Call onDisconnect.
    socket.on('disconnect', () => {
      onDisconnect(socket);
      socket.log('DISCONNECTED');
    });

    // Call onConnect.
    onConnect(socket);
    socket.log('CONNECTED');
  });
```
I ran two instances of my application on two different ports and I also have the redis sever ready to accept connections. But the events are not getting sent from one socket.IO to another. Please can someones suggest any  necessary changes ?
 
Thanks,
Leena

**Comment by nschurmann** [comment]
You are not emitting any messages in your code

**Comment by LeenaBhegade** [comment]
I am emitting messages from different code and I see the emits for the clients which are directly connected to a particular server but not on the client whose server is running on different port

```
function createListener(event, socket) {
  return function(doc) {
    socket.emit(event, doc);
  };
}
```

**Comment by nschurmann** [comment]
Sockets and redis message are different things, the first approach that you need to do is connecting 2 machines using only redis. You can build a playground.js file for that.

So my suggestion would be try to connect first the machines through messages using only redis and don't use websockets until you manage to communicate the machines.

In the last portion of code you are sending a message through a socket, you need to first send it through redis

**Comment by LeenaBhegade** [comment]
hi @nschurmann 

I will read through redis docs and implement as per your answer. Really appreciate your help :-).

Thanks,
Leena

**Comment by LeenaBhegade** [comment]
hey @nschurmann , I implemented the solution , works fine :-) 👍
