### ISSUE TITLE
customHook not working with namespace

### ISSUE THREAD

**Issue by olivier37520** [socketio/socket.io-redis#270]
Hi there, first sorry for my bad english.
I'm trying to use customHook, so i follow the readme who says :
```javascript
// on every node
io.of('/').adapter.customHook = (data, cb) => {
    cb('hello ' + data);
}
// then
io.of('/').adapter.customRequest('john', function(err, replies){
    console.log(replies); // an array ['hello john', ...] with one element per node
});
```

and this works, but i'm using namespace in my app, and naturally i try this :
```javascript
io.of('/somensp').adapter.customHook = (data, cb) => {
    console.log(data); // for debug pupose but never fired
    cb('hello ' + data);
}
// then
io.of('/somensp').adapter.customRequest('john', function(err, replies){
    console.log(err); // gives no error
    console.log(replies); // gives empty array
});
```

but replies is an empty array and debug on the others nodes gives me :
```javascript
socket.io-redis received request {"requestid":"k8Cjd6","type":5,"data":"john"} +1ms
socket.io-redis ignore different channel +0ms
```
As i understand debug, nodes received customhook but ignore it because channels are differents bot both customHook and customRequest use the same nsp... what's wrong there?

So my question is, are customHooks works with custom namespaces or must use root namespace?

Info, nodes are just multiple instances of the same code, everything else works... and adapter config is this : `adapter = redis({ host: 'localhost', port: 6379 });`

**Comment by darrachequesne** [comment]
@olivier37520 I think it's because we subscribe to two channels (request/response) [there](https://github.com/socketio/socket.io-redis/blob/5.2.0/index.js#L111), hence the check in the onrequest method [here](https://github.com/socketio/socket.io-redis/blob/5.2.0/index.js#L180).

What's weird is that your nodes seem to properly receive the request. Could you please try to debug with `PSUBSCRIBE *` with a redis-cli?

**Comment by olivier37520** [comment]
@darrachequesne thanks for your answer, i just find where is the bug. Some days ago i've test customHooks, and i forget to remove weird code.
customHook was defined 2 times on main app loop.
one by `io.of('/somensp').adapter.customHook = (data, cb) => {}` and later by 
```javascript
var somensp = io.of('/somensp');
somensp.adapter.customHook = (data, cb) => {
    if(typeof(data)!=='object') return;
}
```
that's why console.log was never fired and customHook was not handled by the right function. All is working fine now.
