### ISSUE TITLE
Private messages are leaking to global space

### ISSUE THREAD

**Issue by mishelen** [socketio/socket.io-redis#273]
**Faced a problem that private messages accidentially fall into the global room**

The project uses clustering with `throng`. In these processes, clients are created for `socket.io`, which are sewn with `socket.io-redis` adapter. Also, `socket-emitter` is used for the queue in a separate process. The queue also has problem with private messages sending.

The socket-server is created at each restart of the process and is registered in the handler instance. In the `redis` I have a queue with a simple mapping of the user to the socket, and this socket to the user. This allows you to send messages to users, which is very simple:
```js
async socket(id) {
  return this.cache.hget('sockets', id);
}

async getSocketFor(id) {
  const socket = await this.socket(id);
  return socket ? this.io.to(socket) : null;
}
```
And then somewhere: 
```js
try {
      socket = await this.getSocketFor(user);
      if (!socket) { throw new Error(); }
    } catch (err) {
      return;
    }
// ...

socket.emit(event, { message });
```

How all is connected:
```js
const redis = rdsFactory(); // promise-redis

export async function worker(id) {
  try {
    const app = express();
    server = http.createServer(app);

    const wsHandler = io(server);
    wsHandler.adapter(adapter(REDIS_URL));
    const redisClient = await redis.createClient(REDIS_URL);
    const database = await Db.create(MONGO_URI);

    const env = new Env(app, database, wsHandler, redisClient, id);
   //....init
    wsHandler.on('connection', async (socket) => {
      await RootHandler.getInstance(env).register(socket);
    });
    server.listen(PORT);
  } catch (err) {}
}
```

And finishing. I'm give attention to some console output: 
`socket.io-redis publishing message to channel socket.io#/#` when **it was message for socket** taken by `io.to(socket)`

**Comment by mishelen** [comment]
I will supplement the story. I only use private messages. All of them re-use one code above. The most interesting is that some of the messages are sent privately. Part is not. A part can be sent both privately and globally.

About the latter I will tell more. There is a section of code in which messages are sent in a row: synchronously. So, the one that is sent first with different probability is private, then the latter is always global.

There is another thing interesting. If the method emitting messages is called too often, then there is some probability that the last messages will be in the global space.

**Comment by mishelen** [comment]
I have, of course, two suspicions.
- First, it's that the problem can be in a [promisifying wrapper for redis](https://github.com/maxbrieiev/promise-redis).
- that there can be race conditions between two clients. I'll remind you that I have a cluster that directly publishes in socket-redis. And the queue, which also publishes there.

**Comment by KristjanTammekivi** [comment]
Hi, I'm a bit late to the party but I think I've spotted the issue. The problem is that .to modifies the rooms for everybody, and it's not cleaned up until you .emit()

Here you can see that .to doesn't return a new instance of anything:
https://github.com/socketio/socket.io/blob/master/lib/namespace.js#L149

And here you can see the cleanup on emit:
https://github.com/socketio/socket.io/blob/master/lib/namespace.js#L227

**Comment by darrachequesne** [comment]
I think @KristjanTammekivi is right:
```
try {
      socket = await this.getSocketFor(user);
      if (!socket) { throw new Error(); }
    } catch (err) {
      return;
    }
// ... <-- another thread may run `io.emit()` here (i.e. if there's another async / await call)

socket.emit(event, { message });
```

**Comment by mishelen** [comment]
Colleague solve this in such maner

```js
async getSocketFor(id) {
    let socket = null;
    try {
      const socketId = await this.socket(id);
      if (socketId) {
        socket = this.io.of('/').connected[socketId];
        if (socket) {
          return socket;
        }
        return this.io.to(socketId);
      }
      return null;
    } catch (e) { }

    return socket;
  }
```

So mesaages leaks in case when socket was attached to current redis instance when you try to get private namespace from it.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by metroyanno** [comment]
Still up to date

**Comment by darrachequesne** [comment]
@metroyanno let's follow the discussion here: https://github.com/socketio/socket.io/issues/2726

Regarding the initial question:

> In the redis I have a queue with a simple mapping of the user to the socket, and this socket to the user. This allows you to send messages to users [...]

I think this could be refactored by using rooms:

```js
socket.join(user); // join the room identified by the username
// and then later
io.to(user).emit(); // emit to each socket linked to this user
// note: there might be more than one socket, if the user has multiple open tabs for example
```
