### ISSUE TITLE
How to share among nodes supplementary data set to socket object ?

### ISSUE THREAD

**Issue by MatthieuHPP** [socketio/socket.io-redis#275]
Hello,

This is not a bug, I am using a node module based on socket.io that adds supplementary fields to socket object to store data :
```
io.of('/').on('connection', function (client) {
        client.resources = {
            screen: false,
            video: true,
            audio: false
        };
})
```
It seems that these "new" socket fields are not shared among nodes with socket.io-redis, unlike all other functionalities I am using. Is their a simple way to share these supplementary data among nodes ?

Any help will be much appreciated.

Matthieu

**Comment by mishelen** [comment]
only in redis especially you already have it

**Comment by MatthieuHPP** [comment]
Many thanks. I will modify the code and store data inside the dB.
