### ISSUE TITLE
Get all connected sockets, not based on rooms

### ISSUE THREAD

**Issue by SzaboMate90** [socketio/socket.io-redis#277]
Hey there!
I'm wondering if am I able to get all the connected sockets from all clusters? In socket.io with `io.sockets.clients();` I'm able to get all of them and also I've seen with socket.io-redis I can get all sockets from a specific room with `io.in('room3').clients((err, clients) => {` so based on that, maybe to get all sockets is possible too, right? But if yes, how?

I would like to send a message for a specific socket, this is why I asking.

**Comment by BlueSeph28** [comment]
_To send a message to a specific socket, it's little tricky._

In Socket.io 2, every user (socket) create room with the name as the socket id.

What I do is to get the room based on the id of the socket -> I get all the clients inside the room, and check if there is an user inside the room.

- If there is no user inside the room, the room or the user doesn't exist and the user is not connected.
- If there is an user inside the room send the socket with a broadcast to the room (The only user connected to the room is the user).

```
this.io.in(socket.id).clients((err, clients) => {
        if(clients.length > 0 && err == null) {
          this.io.to(toSend.socket).emit(type, data);
        }
}
```

**I think the library need a function to send a message to a specific socket, but it seems that there is no function.**

**Comment by SzaboMate90** [comment]
Thanks! That worked! :)
