### ISSUE TITLE
Multiple Redis nodes in pubClient and subClient not working

### ISSUE THREAD

**Issue by shohelk** [socketio/socket.io-redis#279]
Hi,

We are trying to configure the io.adapter with multiple Redis nodes (for pubClient and subClient). But it does not bind to multiple redis servers. **It defaults to 127.0.0.1:6379**. When we supply single Redis host:port it works.

**This is not working:**

```
const startupNodes = [{
           port: <port>,
           host: "<host-1>"
       }, {
           port: <port>,
           host: "<host-2>"
       }];

io.adapter(redisPubsub({
           pubClient: new Redis.Cluster(startupNodes),
           subClient: new Redis.Cluster(startupNodes)
       }));
```

**This is working:**

```
const pub = {
           port: <port>,
           host: <host-1>
       };

const sub = {
           port: <port>,
           host: <host-2>
       };

io.adapter(redisPubsub({
           pubClient: redis.createClient(pub),
           subClient: redis.createClient(sub)
       }));
```

**Comment by darrachequesne** [comment]
Hi! May I ask what you do mean by "it does not bind to multiple redis servers"?

According to the documentation here (https://github.com/luin/ioredis#cluster), it seems your first example is valid though.

**Comment by knoxcard** [comment]
close ticket?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
