### ISSUE TITLE
can socket.io-redis can be configured with redis-cluster?

### ISSUE THREAD

**Issue by ScorpioKing** [socketio/socket.io-redis#28]

**Comment by chaudhryjunaid** [comment]
The above example seems to be of using a node cluster with a single redis server instead of a cluster of redis servers. Unless I am mistaken and the process for both is mostly the same except providing some sort of special url! 

Please help!

**Comment by iojohnso** [comment]
I am also trying to figure out how socket.io-redis can be connected to a redis cluster.

**Comment by chaudhryjunaid** [comment]
@iojohnso An alternate could be to use socket.io-ioredis, available here: 
https://github.com/GannettDigital/socket.io-ioredis

**Comment by markschmid** [comment]
We also need a working socket.io adapter using a redis cluster. Did anyone solve this problem yet?
The suggestion of @chaudhryjunaid sounds promising, but it seems that prebuilt ioredis clients can only be provided for pub/sub (?)

**Comment by markschmid** [comment]
FYI, https://github.com/GannettDigital/socket.io-ioredis/issues/8

**Comment by darrachequesne** [comment]
By providing an ioredis pub/sub client (implemented in https://github.com/socketio/socket.io-redis/pull/95), you should now be able to connect to a redis-cluster.

Doc: https://github.com/luin/ioredis#cluster

Closing this now :angel:
