### ISSUE TITLE
multiple project on same server

### ISSUE THREAD

**Issue by rafipiccolo** [socketio/socket.io-redis#280]
hello

I have a project using socketioredis on my server and everything works fine.
I consider adding it to another project, but on the same server.
In this case the keys stored in redis will mix, right ?

Is it possible to specify a prefix on the keys stored in redis ?

thx for your help

**Comment by anthony-kenikh** [comment]
First project:
`
const io = require('socket.io')(3000);
const redisAdapter = require('socket.io-redis');
io.adapter(redisAdapter({ key: 'project-1', host: 'localhost', port: 6379 }));
`

And other project:
`
const io = require('socket.io')(3000);
const redisAdapter = require('socket.io-redis');
io.adapter(redisAdapter({ key: 'project-2, host: 'localhost', port: 6379 }));
`

**Comment by rafipiccolo** [comment]
thx !
