### ISSUE TITLE
io.of('/').connected[socketId] does not always return socket object

### ISSUE THREAD

**Issue by joanmooreban** [socketio/socket.io-redis#283]
Before implementing socket.io-redis I used the following to get the socket object:

`var socket = io.sockets.connected[socketId];`

Now that I've implemented socket.io-redis I guess the command to replace it is:

`var socket = io.of('/).connected[socketId];`

However, it returns undefined in many, many cases where the socket actually exists.

I need to know how to get a socket's object by its id but **without** using any callback function since in my initial implementation I used as a return value as showed above and it is being currently used in many parts of the app.

**UPDATE Jun 20th**

I've also unsucessfully tried with `io.of('/').adapter.nsp.connected[socket_id];`. It replies with the right socket object for just some cores, not for all of them, returning undefined most of the time.

**Comment by joanmooreban** [comment]
Anyone on this issue?

**Comment by darrachequesne** [comment]
The socket is not shared accross all nodes:
```js
// node1
io.on('connect', (socket) => {
  // io.sockets.connected[socket.id] === socket
});

// node2
// io.sockets.connected[socket.id] == undefined
```

**Comment by HsinHeng** [comment]
@joanmooreban @jaymehtasa 
if you used multiple nodes architecture, the connected socket object was "only" existed in connected node scope. You may get "undefined" if your wanted socket, which is connected to other node instance. 

So,

solutions:  customHook, customRequest,

You can use customHook to retrieve socket object for specific socketId.
hook the function on your application, and use customRequest to get you wanted socket Object.

**Comment by Manjukb** [comment]
can anyone post working example for this issue ?

**Comment by jaymehtasa** [comment]
@Manjukb you need to use Radis for sharing Socket instance across node cluster.

**Comment by Manjukb** [comment]
@jaymehtasa thanks for your replay 
I tried saving socket connection object to redis but it fails 
Do you have working example ??

**Comment by jaymehtasa** [comment]
@Manjukb 

NodeJS `server.js` file

```js
const socketIoRedis = require('socket.io-redis');
const redis = require('redis');

const redisClient = redis.createClient(<Redis_Port>, <Redis_Host>, {
      no_ready_check: true,
});


if (process.env.REDIS_URL && process.env.REDIS_PORT) {
  IO.adapter(socketIoRedis({ host: <Redis_Host>, port: <Redis_Port>, key: 'socket.io' }));
  logger.info('Connecting Redis');
} else {
  logger.warn('REDIS_URL and REDIS_PORT are not set, socket.io messages will not be shared across servers.');
}

const onConnection = (socket) => {
    const userId = socket.user.id; // Some unique id of the system...

    // Save Socket ID of User to Redis
    redisClient.hset("REDIS_LIVE_SOCKET_USERS", userId, socket.id);

    socket.on('listenToEventSomeGoodEvent', (data) => {
        console.log('listenToEventSomeGoodEvent Fired...');
       
        // Read Socket ID of User from Redis
        redisClient.hget("REDIS_LIVE_SOCKET_USERS", userId, (err, socketId) => {
           if (socketId) {
              io.to(`${socketId}`).emit('sendDataUserEvent', data);
           }
      });
  });
};

const nspChat = io.of('/');
  socketIo = nspChat;
    .on('connection', onConnection);

```

**Comment by Manjukb** [comment]
ok, i use `socket.io-redis` to solve above problem 
i have a problem with getting socket object !! what will `io.to(`${socketId}`)` give is it an socket instance ?? i don't thinks so 
i use `socket.io-request` to pull data from socket client through http 
so in an `express` API i need to  find a specific socket object and communicate with it 
here is the code 
    
> 	var ioreq = require('socket.io-request');
	const socketId = await req.app.redisclient.get('edge-'.concat(req.body.edge_name));
    const ws = req.app.socketio.to(socketId);
    ioreq(ws).request(req.body.method, {body: req.body}).then(function(res) {
        logger.info(res, 'success result ');
        result.json(res);
    });

when i pass `ws` instance to I get `Callbacks are not supported when broadcasting` error from `socket.io-request` lib i was thinking that socket object what i pass is wrong ?? any idea ?? am i doing some mistake here ?

thanks a lot for your help

**Comment by jaymehtasa** [comment]
@Manjukb I will not able to help further as I have never worked with `socket.io-request`.

**Comment by darrachequesne** [comment]
@jaymehtasa I don't understand your example, couldn't you just use a plain emit in that case?

```js
redisClient.hget("REDIS_LIVE_SOCKET_USERS", userId, (err, socketId) => {
  if (socketId) {
    // io.to(`${socketId}`).emit('sendDataUserEvent', data);
    socket.emit('sendDataUserEvent', data);
  }
});
```

Did you mean storing something like the `socket.handshake` object in Redis?

@Manjukb currently, I'm afraid you won't be able to use `socket.io-request` in order to fetch data from a socket connected to another server.

That's a known limitation in the current implementation of acknowledgements.

To share information between servers (though I'm not sure that's the use case here), customHook/customRequest is the way to go (credits to HsinHeng's [anwser](https://github.com/socketio/socket.io-redis/issues/283#issuecomment-437034696)):

```js
// on every node
io.of('/').adapter.customHook = (socketId, cb) => {
  const socket = io.sockets.connected[socketId];
  cb(socket ? socket.handshake : null);
}

// then
const socketId = 'abcd';
io.of('/').adapter.customRequest(socketId, function(err, replies){
  console.log(replies); // an array [null, <handshake>, null, ...] with one element per node
});
```

**Comment by jaymehtasa** [comment]
@darrachequesne 

My example is for sending an event to Recipient User, it might be different than the sender, and can be on any node cluster, so we need to read from the central Redis server, Hope that makes sense.

```
 socket.on('listenToEventSomeGoodEvent', (data) => {
        console.log('listenToEventSomeGoodEvent Fired...');
       
        // Read Socket ID of Recipient User from Redis
        redisClient.hget("REDIS_LIVE_SOCKET_USERS", <recipient_user>, (err, socketId) => {
           if (socketId) {
              io.to(`${socketId}`).emit('sendDataUserEvent', data);
           }
      });
```

**Comment by darrachequesne** [comment]
@jaymehtasa that does make sense! I think you should also be able to use a room for that:

```js
const onConnection = (socket) => {
  const userId = socket.user.id; // Some unique id of the system...
  socket.join(userId);

  socket.on('listenToEventSomeGoodEvent', (data) => {
    console.log('listenToEventSomeGoodEvent Fired...');
       
    io.to(<recipient_user>).emit('sendDataUserEvent', data);
  });
};
```

**Comment by Manjukb** [comment]
@darrachequesne yes i ditched  `socket.io-request` and implemented own way to fetch data from a socket connected to another server
everything else is working as expected , Thanks @darrachequesne @jaymehtasa

**Comment by jaymehtasa** [comment]
@darrachequesne sorry being straight, but I still think the approach you suggested may not work in case of node cluster / horizontally scalable architecture, you need something to centralize socket connections which can Redis or similar service.

the room approach is good when you want to broadcast something for more than one person, in case of one to one communication, I still prefer to go with sending a direct message to the user... even if we use rooms, we need Redis to centralize otherwise, one user might have joined on server-1 and another user might have joined on server-2, they cannot share the room unless it is shared across servers/clusters.
