### ISSUE TITLE
err: ignore unknown room

### ISSUE THREAD

**Issue by icewolfer** [socketio/socket.io-redis#287]
Hello!

I am using `socket.io-redis` within one of my node routes, and I am running into this issue:

`socket.io-redis ignore unknown room DvwAuCksDlwL-ZoyAAAA +5s`

This error repeats for the number of threads I have running. The code that corresponds to the error is a simple emit, `io.to(socketId).emit('data', {data: "hello world!"});`, which I should note, properly emits the data to the proper socket ID, but it does result in errors being called when I run with the debugger. `io` is retrieved via `req.app.get('io')` within the route. Within my index file, I have `socket.io-redis` being instantiated as follows:

`if (cluster.isWorker) {
    const app = require('./app.js');
    const http = require('http');
    const server = http.createServer(app);

    const io = require('socket.io').listen(server);
    const redis = require('socket.io-redis');

    io.adapter(redis({ host: redisConfig.host, port: redisConfig.port }));
    io.on('connection', function(socket) {
        console.log('Adding socket: ${socket.id}');
      socket.on('disconnect', () => {
        console.log(`Deleting socket: ${socket.id}`);
      });
    });

    app.set('io', io);
    server.listen(3036);
}`

I am fully aware that I may be using the package incorrectly. If so, could someone kindly inform me on what I'm doing wrong? Thanks!

**Comment by icewolfer** [comment]
I am also curious to know how `socket.io-redis` handles emitting data and retrieving clients. Previously, I was running `io.of('/').adapter.clients`, and it seems to cause errors for me as well. The output I received was as follows:

`socket.io-redis waiting for 9 responses to "clients" request +1ms
  socket.io-redis received request {"requestid":"AnU76r","type":0,"rooms":[]} +1ms`

Followed by several lines of `socket.io-redis ignoring unknown request +1ms`.

As with my emit call, the call to retrieve the list of socket IDs did return correctly, but resulted in several error emissions. 

Is this the intended behavior? Sorry for my unfamiliarity with `socket.io-redis`.

**Comment by darrachequesne** [comment]
@icewolfer `ignore unknown room` is a log indicating the given node should not decode the packet, because the node has no room with that name (the rooms are stored at the node level, not shared accross all nodes). So I'm not sure there is any problem here?

**Comment by knoxcard** [comment]
@icewolfer - close ticket?

**Comment by Xuhao** [comment]
@icewolfer 

have you call `leaveAll` on that socket ? `leaveAll` will leave all rooms include itself. so any event emit to it won't received.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
