### ISSUE TITLE
Naming Redis Channels Properly

### ISSUE THREAD

**Issue by moeabdol** [socketio/socket.io-redis#289]
I'm facing a problem trying to properly name channels in redis.
In the following I use 'rtt_' as a prefix.
```
const io = require('socket.io')(server);

io.adapter(redisAdapter({
  host: REDIS_HOST,
  port: REDIS_PORT,
  key: 'rtt_',
  pubClient: redisPub
}));

```
And now when I

```io.to(`riders/${riderInfo.id}`).emit('riderOnline', riderInfo);```

And then open my redis-cli, I find that the channel is actually named

```rtt_#/#riders/1#```

Is there a way I can fix this naming issue. I eventually want something like

```riders/1```

Thanks

**Comment by darrachequesne** [comment]
The format of the channel is `prefix + '#' + namespace + '#' + room + '#'`. ([ref](https://github.com/socketio/socket.io-redis#protocol))

So:
- prefix: `rtt_` 
- namespace: `/`
- room: `riders/1`

Gives `rtt_#/#riders/1#`. Out of curiosity, what is your use case?

**Comment by knoxcard** [comment]
@moeabdol - close ticket?
