### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by peteruithoven** [socketio/socket.io-redis#29]
What would be the best way to handle syncing namespace creation among clustered node.js instances? 
When one instance creates namespaces and a client connects to another instance it won't find these namespaces and can't connect. 
Is this something socket.io-redis should do or should I write my own pub/sub system to handle this?

**Comment by wonderdogone** [comment]
interesting. Are your namespaces being created dynamically. Say "per session" for example?

**Comment by darrachequesne** [comment]
Seems solved. Please reopen if not.

Closing this now :angel:
