### ISSUE TITLE
Memory requirements? Hosting Redis in AWS ElastiCache

### ISSUE THREAD

**Issue by maxpaj** [socketio/socket.io-redis#290]
What are the requirements on memory in the Redis database? 

Is any data persisted or is it deleted immediately once the information has been consumed by all Socket.IO servers connected to the Redis?

**Comment by darrachequesne** [comment]
No data is kept on the nodes, only the PUB/SUB mechanism is used, so it should be mostly CPU-bound.

**Comment by maxpaj** [comment]
Thanks! Let's close this one.
