### ISSUE TITLE
The function that takes a list of sockets in a room takes a long time.

### ISSUE THREAD

**Issue by SimWonKim** [socketio/socket.io-redis#295]
Currently I am using AWS. I am using redis with elasticache.

The server grows and shrinks due to auto-scaling, and when the server shrinks, socket.io is disconnected and tries to reconnect to the other server.

After the re-connection is successful, the function that calls the socket IDs in the room will take 5 seconds. Below is a log of the redis verified by monitor.

<img width="1436" alt="2018-10-29 12 01 16" src="https://user-images.githubusercontent.com/40909922/47617827-dc7ced80-db0e-11e8-9bdf-14c7355cf399.png">

I did a search for three days to solve this problem, but I did not think anyone had the same problem. So I leave a post here.

I can not speak English very well. This article may be strange to deliver using a Google Translator. Sorry.

**Comment by knoxcard** [comment]
I noticed the code contains a lot of setTimeouts for exactly 5 seconds.

```
var requestsTimeout = opts.requestsTimeout || 5000;
```

@darrachequesne

**Comment by darrachequesne** [comment]
When a server is killed, there might be a small period during which the requester node waits for N answers (N being the number returns by the `numsub` command) but only gets (N - 1) answers.

In that case, the command will then timeout after 5 seconds (the default value of the  `requestsTimeout` option).

Everything should go back to normal after a few seconds though.
