### ISSUE TITLE
Does socket.io-redis keep connections upon restart in cluster mode?

### ISSUE THREAD

**Issue by cschwaderer** [socketio/socket.io-redis#296]
I am using socket.io-redis withing Sails.js in a PM2 cluster. I had hoped that this way when doing `pm2 reload` socket-connections to the client would be kept.

Like

> Process 1: Oh, I got the SIGINT, however, I have open connections to clients. Hey, process 2, could you please take over?
Process 2: Yes, sure! Just pass your your connections to me. I'll take care of them!
Process 1: Great! Now I can shutdown
Process 2: Oh! Now it's me getting SIGINT. Process 1, is there anything you can do about it?
Process 1: Hey! Luckily, I'm already there again! Just give me your connections, process 2!
Process 2: Ok. Here are my connections! Now I'll restart

However, it doesn't work. If I do `pm2 reload` the clienct connections might disconnect if they happen to try to `ping` right in the moment when their process is being restarted. And that causes minor problems for me.

So, question is: Does socket.io-redis provide some mechanism for interruption-free socket-connections? Meaning that it just doesn't work for me because I've misconfigured it. Or is this feature simply not implemented or out-of-scope?

**Comment by darrachequesne** [comment]
> Does socket.io-redis provide some mechanism for interruption-free socket-connections?

No. `socket.io-redis` is only used to broadcast events between Socket.IO servers.

Killing a server will always force the clients that were connected to this server to reconnect.
