### ISSUE TITLE
adapter.clients incorrect results cluster mode

### ISSUE THREAD

**Issue by infnada** [socketio/socket.io-redis#297]
Based on the next code i always get different results and this should not happen:

		return new Promise(function (resolve, reject) {

			// Get all sockets in this game
			req.io.of('/').adapter.clients(["someRoom"], function (err, clients) {
				if (err) return reject(err);

				console.log(clients);

				return resolve();
			});

		})

Results:
[ '0mWH5zHjshG4gy0HAAAA', 'wB6oGpDOyTxZKSkhAAAB' ]
[ 'UXSW_jyGKnZKCF_SAAAA' ]
[ '0mWH5zHjshG4gy0HAAAA', 'wB6oGpDOyTxZKSkhAAAB' ]
[ '0mWH5zHjshG4gy0HAAAA',  'wB6oGpDOyTxZKSkhAAAB', 'UXSW_jyGKnZKCF_SAAAA' ]
[ 'UXSW_jyGKnZKCF_SAAAA' ]
[ 'UXSW_jyGKnZKCF_SAAAA' ]
[ '0mWH5zHjshG4gy0HAAAA', 'wB6oGpDOyTxZKSkhAAAB' ]
....

This should always return all 3 users in this room.
[ '0mWH5zHjshG4gy0HAAAA',  'wB6oGpDOyTxZKSkhAAAB', 'UXSW_jyGKnZKCF_SAAAA' ]

Using latest version of socket.io, socket.io-adapter, socket.io-redis, etc
Node v8.11.1

NOTE: there are a lot more internal code happening. This code is called once per POST request.

**Comment by knoxcard** [comment]
@infnada - are you calling **.leave()** anywhere in your code?

**Comment by knoxcard** [comment]
"This code is called once per POST request." - are you mixing AJAX/XHR requests with socket.io?  I was doing the same thing and ran into a bunch of probllems.  Then I finally made sense of it all.  It was a crazy combination of timing and req.session.  I'd have to see your code logic to determine the issue.

**Comment by xr** [comment]
i had the similar issues, have you guys had any updates on this? @infnada @knoxcard

**Comment by syd619** [comment]
Bump

**Comment by darrachequesne** [comment]
This is now fixed in [5.3.0](https://github.com/socketio/socket.io-redis/releases/tag/5.3.0) and later.
