### ISSUE TITLE
Redis large concurrency exception

### ISSUE THREAD

**Issue by 759325100** [socketio/socket.io-redis#298]
When redis performs a large amount of data read and write.
I found the following error message in the redis log:
<code>
subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
</code>
I flipped through the official documentation of Redis, it should be the sub buffer reached the limit, but I don't understand why this is.

**Comment by darrachequesne** [comment]
@759325100 Hi! Did you find a solution to your issue? Could you please share it, for future readers?
