### ISSUE TITLE
use load balance in my project,i have 2 socket.io server.

### ISSUE THREAD

**Issue by tianhuihui4217** [socketio/socket.io-redis#299]
use load balance in my project,i have 2 socket.io server. the result of two socket.io server is that send message client can't receive msg, i see client can connect on server,i find some way to solve this problem.
finally,i find this lib it is helpful to my project , now, clients can receive msgs, thanks a lot, i'm chinese deploveper.

**Comment by darrachequesne** [comment]
Hi @tianhuihui4217 , that's great! Is there something we could improve in the documentation?

Good luck for your projects!

**Comment by knoxcard** [comment]
@tianhuihui4217 - close ticket?

**Comment by knoxcard** [comment]
@tianhuihui4217 - that is so great to hear!  Wish github had a section to post and store comments such as yours.  Since this is labeled as an issue, can you go ahead and **close this ticket**?  This will still be viewable when people Google this project.
