### ISSUE TITLE
Handle error when redis shuts down

### ISSUE THREAD

**Issue by krisitown** [socketio/socket.io-redis#301]
Hello, I have this little node server that communicates with a redis server, I just need some advice how I can make it so the nodejs app doesn't crash when the redis server goes down. I need it to not crash and try and reconnect to redis, but I am not very experienced with using sockets so I am having quite the trouble, if somebody can help me I would be very greatful!
```

var express = require('express');
var app = express();
var server = require('http').createServer(app);
var socket = require('socket.io');
var redis = require("redis");
var redisAdapter = require('socket.io-redis');

server.listen(config.nodejs.port, function () {
    console.log('listening on ' + config.nodejs.port);
})

var io = socket.listen(server);
io.set("transports", ["xhr-polling", "websocket", "polling", "htmlfile"]);
io.adapter(redisAdapter({host: config.redis.address, port: config.redis.port}));
io.on('connection', function (client) {
    console.log('Client connected...');
    var sessionId = client.handshake.query.searchSessionId;
    client.join(sessionId);
    console.log('room ' + sessionId)
});


var searchResultQueue = redis.createClient({host: config.redis.address});
var blpopQueue = function () {
    searchResultQueue.blpop('socketio-search-result', 5, function (err, data) {
            blpopQueue();
            if (data) {
                var timestamp = data[1].substring(60, 73);
                var eventId = data[1].substring(14, 46);
                if (Date.now() - timestamp < searchResultTtl) {
                    console.log(eventId + ' ' + timestamp)
                    io.sockets.in(eventId).emit('flights/' + eventId, data[1]);
                } else {
                    console.log(eventId + ' skipped duo expired ttl')
                }
            }
        }
    )
}

blpopQueue();
```

**Comment by knoxcard** [comment]
```
	var redis = require('redis').createClient({
	  port: nconf.get('redis:port'),
	  retry_strategy: options => {
	    if(options.error && options.error.code === 'ECONNREFUSED')
	      return new Error('Connection Refused')
	    if(options.total_retry_time > 1000 * 60 * 60)
	      return new Error('Retry Time Exhausted')
	    if(options.attempt > 10)
	      return undefined
	    return Math.min(options.attempt * 100, 3000)
	  }
	}).on('connect', ret => {
	  cb(redis)
	}).on('error', err => {
	  throw 'app.redis err: ' + err
	})
```

**Comment by knoxcard** [comment]
`
var redis = require('redis').createClient({
  port: nconf.get('redis:port'),
  retry_strategy: options => {
    if(options.error && options.error.code === 'ECONNREFUSED')
      return new Error('Connection Refused')
    if(options.total_retry_time > 1000 * 60 * 60)
      return new Error('Retry Time Exhausted')
    if(options.attempt > 10)
      return undefined
    return Math.min(options.attempt * 100, 3000)
  }
}).on('connect', ret => {
  cb(redis)
}).on('error', err => {
  throw 'app.redis err: ' + err
})
`

**Comment by knoxcard** [comment]
@krisitown - close ticket?

**Comment by krisitown** [comment]
> ```
> var redis = require('redis').createClient({
>   port: nconf.get('redis:port'),
>   retry_strategy: options => {
>     if(options.error && options.error.code === 'ECONNREFUSED')
>       return new Error('Connection Refused')
>     if(options.total_retry_time > 1000 * 60 * 60)
>       return new Error('Retry Time Exhausted')
>     if(options.attempt > 10)
>       return undefined
>     return Math.min(options.attempt * 100, 3000)
>   }
> }).on('connect', ret => {
>   // redis connected
>   // continue with program logic
> }).on('error', err => {
>   throw 'app.redis err: ' + err
> })
> ```

Thanks for the answer, but there are still some problems. 
At least the application doesn't crash now, but now it get's stuck in a loop I think. I added some console.log lines and see that the application tries to reconnect only twice.
Is there any documentation on this retry_strategy function, I don't understand what it is supposed to return, and how I can configure the timeout and the amount of times it can try and reconnect.
I added the strategy to the part of the code where I create the client.

Do you have any idea why it only loops 2 times and then stops doing anything?

**Comment by krisitown** [comment]
Yes, thank you very much!

**Comment by knoxcard** [comment]
@krisitown - great to hear!  You have to close the ticket, you should see the close button at the bottom of this thread.

**Comment by HosseinAgha** [comment]
This still happens for me. I use `ioredis` as client

**Comment by ahmadzahabi1** [comment]
io.of('/').adapter.on('error', function(error){
            utils.logError(error, "WebSocketIOServer --> io :");
        });

**Comment by ahmadzahabi1** [comment]
> This still happens for me. I use `ioredis` as client. I'm listenning on `error` even of course. It logs the error and then crashes the server.

Dear Hossein, check below my comment.

**Comment by HosseinAgha** [comment]
Thanks @ahmadzahabi1, your solution fixed it for me.
