### ISSUE TITLE
Does the callback in customHook work with Redis Cluster?

### ISSUE THREAD

**Issue by hmoush95** [socketio/socket.io-redis#311]
I'm trying to use the callback feature for customRequest/customHook while using a Redis Cluster using IORedis.

When one websocket node sends a customRequest, all of the websocket nodes hit the customHook just fine. However, the requesting node does not receive the callback response from most of the servers most of the time. When I switch to simply using a single Redis node (as opposed to a Redis Cluster), the above works fine.

Does callback not work when using Redis Cluster?

**Comment by hmoush95** [comment]
When this happens, the error from the customRequest callback reads:

Error: timeout reached while waiting for customRequest response

And it only receives the response from itself, and not other nodes. This does not happen when using a single Redis node. All socket servers send their response without timing out when using a single Redis node.

**Comment by JordanPawlett** [comment]
I'm experiencing similar behaviour. When using Redis cluster I only receive a response from 1/3 servers at a time.
Whilst receiving `Error: timeout reached while waiting for customRequest response` around 60% of the time.

**Comment by hmoush95** [comment]
fyi we never got this solved and ended up needing to work around it. Our customHook was meant to read local data from each node and then use the callback to aggregate that data on the requesting node before emitting a single response it to the requesting client.

Our workaround had the customHook read local data from each node and then had each node emit their own response to the requesting client with their own local data. It is up to the client to aggregate the data on their end. Sadly this comes with drawbacks where the client may not know when it has received "all" the responses and may be left listening indefinitely (we have it stop listening after some timeout).

(you can have each node send the response to a specific client using 

`nsp.to(clientSocketId).emit('eventName', localData);`

where the `clientSocketId` gets passed by you into the customHook via the customRequest argument)

**Comment by JordanPawlett** [comment]
Can confirm that the fix from that issue is working for me consistently across my tests.

**Comment by JordanPawlett** [comment]
[5.3.0](https://github.com/socketio/socket.io-redis/releases/tag/5.3.0) has just been released, with the fix mentioned above.
This issue looks to be resolved.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/commit/7a190755c01732d1335199732e7b0eb5a1fb1f9e, which is indeed included in [5.3.0](https://github.com/socketio/socket.io-redis/releases/tag/5.3.0) :+1:
