### ISSUE TITLE
remoteJoin('socket id', 'room name') does not work properly, or am I misunderstanding something?

### ISSUE THREAD

**Issue by lhxatus** [socketio/socket.io-redis#318]
I was using `remoteJoin` to assign sockets to custom rooms such as room1, room2, etc..
but each socket was only assigned to the room with socket.id as its name.
And I checked existing rooms by using `allRooms`, I couldn't find any room with my custom naming.

` io.of('/').adapter.remoteJoin(socket.id, 'room1', (error) => {....})`

```
io.of('/').adapter.clientRooms(socket.id, (err, rooms) => {
                if (err) { /* unknown id */ }
                console.log(`${socket.id} joined rooms: \`, rooms);
});
```

Then I got console log like this 

`gDdHAZlJF8tiQ-OUAAAB joined rooms:  [ 'gDdHAZlJF8tiQ-OUAAAB' ]`

I was expecting to get 

`
gDdHAZlJF8tiQ-OUAAAB joined rooms:  [ 'room1' ]`

Did I make any mistake, or am I misunderstanding something?

`io.of('/').adapter.allRooms`, it only shows an array of socket.id

```
"socket.io": "^2.0.3",
"socket.io-redis": "^5.2.0" 
```

redis version 5.0.5

**Comment by knoxcard** [comment]
It definitely works.  Sounds like you are not using a callback.

```
      websocket.of('/').adapter.clientRooms(socket.id, (err, rooms) => {
        // if (err) { /* unknown id */ }
        console.log(socket.id + ' joined rooms: ', rooms)
      })
```

**Comment by lhxatus** [comment]
@knoxcard  I wasn't using error callback for remoteJoin, the error actually was returned to front end which I didn't notice last night. 

An error happened during remoteJoin, that's why I couldn't find those rooms.

```
Error: timeout reached while waiting for remoteJoin response
    at Timeout._onTimeout (./node_modules/socket.io-redis/index.js:591:46)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) 
```
redis 5.0.5 in local environment and I connected redis like this.

`io.adapter(redisAdapter({host: 'localhost', port: 6379}))`

**Comment by knoxcard** [comment]
Change host to ip address: 127.0.0.1, no dns lookup required.

**Comment by lhxatus** [comment]
Thanks for your help. I tried to add more requestsTimeout, but the error is still there. 

And I think it should be the same problem in #210

**Comment by knoxcard2** [comment]
Sounds good.  Close ticket?
