### ISSUE TITLE
How to define username & password for postgresql connection

### ISSUE THREAD

**Issue by Kaliph** [socketio/socket.io-redis#322]
Hello, my postgresql uses a username and a password for authentication. How can I set those when defining connection object? { host: 'localhost', port: 5432 }
Is something like this possible ? { host: 'localhost', port: 5432, username: xxxx , password xxxxxxxx }

Thankyou

**Comment by darrachequesne** [comment]
Please see the example [here](https://github.com/socketio/socket.io-redis#custom-client-eg-with-authentication):

```js
const redis = require('redis');
const redisAdapter = require('socket.io-redis');
const pubClient = redis.createClient(port, host, { auth_pass: "pwd" });
const subClient = pubClient.duplicate();
io.adapter(redisAdapter({ pubClient, subClient }));
```
