### ISSUE TITLE
Question: Emiting on socket ID will work with multiple socket.io instances?

### ISSUE THREAD

**Issue by jaykumarthaker** [socketio/socket.io-redis#324]
Basically we do keep track of socket_ids associated with each user through central storage (ioredis). Consider if userA having socket id "userA_socket_id" is connected to socket.io instance X. Now let's say userB who is connected to socket.io instance Y, wants to send data to userA, hence he gets userA's socket id (from ioredis) and then do:

`io.to(userA_socket_id).emit("event_name", data);`

so, will this work? will this request be forwarded from socket.io instance Y to X?

**Comment by darrachequesne** [comment]
> will this request be forwarded from socket.io instance Y to X?

Yes, that is exactly the use case covered by this library.

> hence he gets userA's socket id (from ioredis) and then do:

I think you can even take full advantage of the Room concept (documented [here](https://socket.io/docs/v3/rooms)):

```js
// instance X
io.on("connection", (socket) => {
  socket.join("userA");
});

// instance Y
io.to("userA").emit("hello");
```

In this case, you don't even need to track the socket IDs associated with each user.
