### ISSUE TITLE
ERR unknown command 'pubsub' while checking sockets connected to a specific room in clustur mode.

### ISSUE THREAD

**Issue by jagmohan47** [socketio/socket.io-redis#325]

**Comment by KnutHjelvik** [comment]
I got this issue too. When i skip clustering it is working fine....

**Comment by jaggi47** [comment]
What is your redis version? I updated the version and afterthat worked fine in clustur mode as well.

**Comment by KnutHjelvik** [comment]
2.4.5, windows

**Comment by jaggi47** [comment]
Update it to higher version

**Comment by KnutHjelvik** [comment]
I Will try tonight. Thanks.

I Just figured out that 2.9 is out. Hopefully that helps.

**Comment by KnutHjelvik** [comment]
That fixed it! :D Thanks alot.

**Comment by jagmohan47** [comment]
Thanx a lot @jaggi47 . i am closing the issue.
