### ISSUE TITLE
Access a specific connection from one node to another node

### ISSUE THREAD

**Issue by Hesamp** [socketio/socket.io-redis#326]
hi , 
How can I Access a specific connection from one node to another node ?
If you need to use custom Request and custom hook, how to do it?

`namespaceIo.adapter.customHook = function (data, callback) {
					if (typeof callback !== 'function') {
						return;
					}
					if (data && data.message === 'getSocketObject') {
						namespaceIo.adapter.clients((err, clients) => {
							let dd = clients.find(function (element) {
								return element === data.room;
							});
							if (dd) {
								if (!namespaceIo.connected.hasOwnProperty(dd)) {

									// socket.sockets[dd] = namespaceIo.to(dd);
									// eslint-disable-next-line no-console
									// console.warn('add to node : ', dd); // an array containing all connected socket ids
									return callback(true);
								} else {
									namespaceIo.adapter.remoteJoin(data.room, data.room, function (err) {
										// eslint-disable-next-line no-console
										console.warn(err);
									});
									return callback(true);
								}
							}
							return callback(false);
						});
					} else {
						callback();
					}
				};

				namespaceIo.adapter.customRequest({
					message: 'getSocketObject',
					room: socket.id,
				}, function (err, replies) {
					// eslint-disable-next-line no-console
					console.log('replies :', replies);
				});`

**Comment by bloodymind** [comment]
I have the same question! any way to do this?

**Comment by harishasan** [comment]
Same question

**Comment by darrachequesne** [comment]
For future readers: please check https://socket.io/docs/v4/server-instance/#Utility-methods
