### ISSUE TITLE
socket.io-redis - Redis connection ETIMEDOUT

### ISSUE THREAD

**Issue by yhugow** [socketio/socket.io-redis#328]
Hi there,
Anyone experience this?
I can’t connect my redis. It always says “_**Redis connection to redis-306657c7-withfbtesting-69cb.aivencloud.com:10104 failed - connect ETIMEDOUT 35.221.224.142:10104**_”

```
var redisAdapter = require('socket.io-redis');

io.adapter(redisAdapter({ 
        host: 'redis-306657c7-withfbtesting-69cb.aivencloud.com', 
        port : 10104,
        auth_pass: 'yazrwoe092cvzm9r',
}));
```

<img width="872" alt="Screen Shot 2020-01-08 at 6 23 41 PM" src="https://user-images.githubusercontent.com/17878591/71970671-13d34800-3244-11ea-9866-8dec68bbc69a.png">

**Comment by JailBreakC** [comment]
same issue with me.

**Comment by moisescorreo** [comment]
Same with me
 `const io = require('socket.io')(socketPort)
const redisAdapter = require('socket.io-redis');
io.adapter(
  redisAdapter({
    host: "asddasds.0001.use1.cache.amazonaws.com",
    port: "6379",
  }, {
    requestsTimeout: 30000
  })
);
`

**Comment by yhugow** [comment]
Hi there,
It's now working I'm using redislabs.com instead of aivencloud.com.

Here's my current configuration:
```
var redisAdapter = require('socket.io-redis');
io.adapter(redisAdapter({ 
        host: 'redis-12312.c10.us-east-1-2.ec2.cloud.redislabs.com', 
        port : 10112,
        auth_pass: 'my_auth_pass',
}));
```
Hope it helps.

**Comment by qwe123wsx** [comment]
same problems here, ETIMEDOUT error causes my app to crash, tried

`io.on('error', () => {})`

but still crash

**Comment by JeffreyTaylor** [comment]
I get the same error when using AWS Elasticache.

**Comment by rafakwolf** [comment]
My app is also crashing here, there's a way to avoid the app to crash? 
thanks!

**Comment by darrachequesne** [comment]
Please see https://github.com/socketio/socket.io-redis#client-error-handling

```js
io.of('/').adapter.on('error', (err) => {
  // ...
});
```
