### ISSUE TITLE
Using remoteJoin I see no channels listed with redis-cli > pubsub channels

### ISSUE THREAD

**Issue by stuartambient** [socketio/socket.io-redis#334]
I created a simple subClient and pubClient.  If I use them in my code then I get a list running pubsub channels in the redis-cli and the adapter subcription_set is populated when subscribe channels.  If using just the native api, with remoteJoin , emit, etc, I see no channels listed except of the namespace request and response. 

So which approach do I take ? I want to take advantage of Redis pubsub.

**Comment by darrachequesne** [comment]
Please see https://github.com/socketio/socket.io-redis#how-does-it-work-under-the-hood
