### ISSUE TITLE
Shared Redis instance

### ISSUE THREAD

**Issue by dispatchqueue** [socketio/socket.io-redis#335]
Hi there,
There's any way to share a single Redis instance for multiple socket.io applications?
I found that the adapter supports an option named [`key`](https://github.com/socketio/socket.io-redis#adapteropts), but I'm not sure it is the correct way.

```
io.adapter(redisAdapter({
    key: 'app-1',
    host: 'localhost',
    port: 6379
}));
```

**Comment by darrachequesne** [comment]
Yes, that's the correct way. The channels will use the given prefix (`app-1`, in your example), so that the messages won't be mixed up.
