### ISSUE TITLE
Maintenance Needed -- Are any of the maintainers monitoring?

### ISSUE THREAD

**Issue by ThreeDfish** [socketio/socket.io-redis#339]
This library has not been updated in years.  There are several good valid pending pull requests that although needs a small amount of work, have been around for a while and raise valid issues.

The dependencies need to be updated to current versions that have been improved and had bug fixes.

Where are the maintainers?  How can we get this updated?   If no pull requests are being accepted, perhaps somebody else can take over the maintenance.

**Comment by darrachequesne** [comment]
Hi, sorry for the delay.

I have merged some pull requests and released the latest change. Any particular issue that would need our attention?

**Comment by darrachequesne** [comment]
@DispatchCommit I think both [node-redis](https://github.com/NodeRedis/node-redis) and [ioredis](https://github.com/luin/ioredis) support TLS/SSL already, aren't they?

Let's close this, as most pull requests have been merged/commented.

**Comment by DispatchCommit** [comment]
#351 resolves it, so LGTM.
