### ISSUE TITLE
[Question] How to send a message to Specific Client in a Room in a Cluster Mode  

### ISSUE THREAD

**Issue by bloodymind** [socketio/socket.io-redis#340]
Dear all,

I'm using Socket.io-redis and Socket.io v2 on Cluster-Mode, I have an issue when it comes to sending a direct message to a particular person. let me explain:

I have 4 users all joining the same room, each one the users have a sticky session with one of my backends. when a product a message in the room `socket.to('room1').emit('hello', "Hello clients");` i can see that the message is delivered. But when I try to send a message to a particular! first there is such thing in the documentation, I only try to send it using the internal users like this:

`io.sockets.connected[user.id].join('room1')`

I know that the user that I'm looking for may or may not exist in the node. but is there is a way to send a message to a particular user using this socket adapter? maybe a shared Sockets list somehow? or communication a server to server to do so!?

What would you do to solve that issue?

Dependencies:

```
"socket.io": "^2.3.0",
"socket.io-redis": "^5.2.0",
```

Thanks in advance.

**Comment by FanFataL** [comment]
```
io.to(socketId).emit(...)
```

**Comment by ganeshro8** [comment]
Nothing
