### ISSUE TITLE
Is redis 5.0.8 supported?

### ISSUE THREAD

**Issue by deepinder10** [socketio/socket.io-redis#341]
I upgraded my redis version from v3 to v5.0.8 and socket.io didn't deliver events to connections on different node, only users connected on the same node got the events.

**Comment by darrachequesne** [comment]
The CI seems to say version `5.0.4` is OK: https://travis-ci.org/github/socketio/socket.io-redis/jobs/694639681#L125

Do you get any error upon connection?

**Comment by deepinder10** [comment]
No, I didn't receive any errors but the events from other nodes were not received. My current version 3.2.8 works pretty well.

**Comment by darrachequesne** [comment]
I'm not able to reproduce in local, when running a node with [docker-compose.yml](https://github.com/socketio/socket.io-redis/blob/master/docker-compose.yml).

Could you please provide a simple case reproducing the issue?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
