### ISSUE TITLE
?EIO=3&transport=websocket&sid=QwJ4PS0IUeGNbGu8AAEd' failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by pawansgi92** [socketio/socket.io-redis#346]
When I try to run socket.io on two server using AWS Load balaancer I am getting this error any solution of this..

But everything working fine if I run on single server.

thanks in adavance 

**Error: ?EIO=3&transport=websocket&sid=QwJ4PS0IUeGNbGu8AAEd' failed: WebSocket is closed before the connection is established.**

Code Sample on server side

var server = app.listen("80");
var io = require('socket.io').listen(server);

// redis enable 
var redis = require('socket.io-redis');
io.adapter(redis({host: 'xxx.redis host url ', port: 6379}));

Do  I need to add anything more in it for running on two server

And If i try to connect to Aws redis cluster how can i do it in above code

**Comment by csmoakpax8** [comment]
@pawansgi92 i am experiencing a very similar situation. I am still investigating. But I am wondering if the initial connection is not being broadcasted across nodes. so during the socket.io handshake one request goes to instance 1, then other requests go to instance 2. Not the handshake is invalid and starts over. 

One solution would probably be to turn on sticky sessions on the LB. but its not ideal.

**Comment by pawansgi92** [comment]
@csmoakpax8  It is working good on my side without using the sticky sessions ... Issue in redis.

**Comment by csmoakpax8** [comment]
@pawansgi92 Was there a fix in a recent version of redis that fixed this? What version are you on?

**Comment by BFalls158** [comment]
@pawansgi92 Any chance you could explain what was wrong with redis? Running into the same issue, but unsure where to go from here. Looks like redis isn't getting any broadcasts, but the exact same setup works in a different cluster.

**Comment by darrachequesne** [comment]
Please see https://socket.io/docs/v3/using-multiple-nodes/
