### ISSUE TITLE
Unable to connect to redis server with `rediss://`

### ISSUE THREAD

**Issue by maffpool** [socketio/socket.io-redis#347]
Hello !

I'm using DigitalOcean redis managed DB, which only accepts tls connections.
In the last version of https://github.com/NodeRedis/node-redis (starting from 3.x), the `rediss://` protocol is accepted.
Is there a chance you upgrade to node-redis 3.x soon ?

**Comment by willoughby** [comment]
+1

**Comment by darrachequesne** [comment]
Released as [5.4.0](https://github.com/socketio/socket.io-redis/releases/tag/5.4.0) :fire:
