### ISSUE TITLE
Feature | remoteJoin | accept array or  string for room 

### ISSUE THREAD

**Issue by matth-c3** [socketio/socket.io-redis#349]
Hello @darrachequesne ,

Would it be constraining to accept an `array` for the method `remoteJoin` as follow : 

**as a string**
```
io.of('/').adapter.remoteJoin('<my-id>', 'room1', (err) => {
  if (err) { /* unknown id */ }
  // success
});
```

**as an array**
```
io.of('/').adapter.remoteJoin('<my-id>', ['room1','room2', 'room3'], (err) => {
  if (err) { /* unknown id */ }
  // success
});
```

Or there is maybe a reason why it was not implemented ? 

Thanks

**Comment by darrachequesne** [comment]
@matth-c3 `#remoteJoin()` came before we added the ability to join multiple rooms at once with `#join(rooms)`, that's why it's not implemented.

Could you please open a pull request? I'll be happy to merge it.

**Comment by matth-c3** [comment]
Hello @darrachequesne , 

Sure I can look at it next week.

Thanks
