### ISSUE TITLE
remoteDisconnect not working properly 

### ISSUE THREAD

**Issue by ritikasib** [socketio/socket.io-redis#350]
on socket disconnection I am trying to remotely disconnect the socket id.

`currentNamespacedSocket.on('disconnect', reason => {
        logger.info('[disconnect]', {
          date: new Date(),
          reason,
        });
        currentNamespacedSocket.adapter.remoteDisconnect(currentNamespacedSocket.id, false, err => {
          if (err) {
            logger.error('[disconnection] error', {
              date: new Date(),
              namespace,
              socket_id: currentNamespacedSocket.id,
              reason,
            });
          }
          /** emit some socket events by getting data from custom hook **/
          }`

but this remoteDisconnect goes to error condition and when i fetch sockets data through custom hook they give me socket data of disconnected socket also as remoteDisconnect has failed.

I also tried to do this remoteDisconnect on `disconnecting` socket io  event but that gave fatal error.
 `internal/async_hooks.js:138
node-server-1_1  |     fatalError(e);
node-server-1_1  |     ^
node-server-1_1  |
node-server-1_1  | RangeError: Maximum call stack size exceeded
node-server-1_1  |     at RandomBytes.emitInitNative (internal/async_hooks.js:138:5)
node-server-1_1  |     at Object.randomBytes (internal/crypto/random.js:45:10)
node-server-1_1  |     at uid (/var/www/html/node_modules/uid2/index.js:42:25)
node-server-1_1  |     at Redis.remoteDisconnect (/var/www/html/node_modules/socket.io-redis/index.js:682:21)
node-server-1_1  |     at Socket.<anonymous> (/var/www/html/dist/app.js:171:41)
node-server-1_1  |     at Socket.emit (events.js:180:13)
node-server-1_1  |     at Socket.emit (/var/www/html/node_modules/socket.io/lib/socket.js:140:10)
node-server-1_1  |     at Socket.onclose (/var/www/html/node_modules/socket.io/lib/socket.js:445:8)
node-server-1_1  |     at Socket.disconnect (/var/www/html/node_modules/socket.io/lib/socket.js:480:10)
node-server-1_1  |     at Redis.remoteDisconnect (/var/www/html/node_modules/socket.io-redis/index.js:686:14)
node-server-1_1  |     at Socket.<anonymous> (/var/www/html/dist/app.js:171:41)
node-server-1_1  |     at Socket.emit (events.js:180:13)`
Can some one help me with this ?  Thanks in advance

**Comment by reidelgp** [comment]
same situation!

**Comment by darrachequesne** [comment]
> on socket disconnection I am trying to remotely disconnect the socket id.

Could you please explain what is your use case? The disconnected socket only exists on the current node, so there should be no cleanup to do. Am I missing something?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
