### ISSUE TITLE
How to determine if a `room` to join is remote or local?

### ISSUE THREAD

**Issue by cinout** [socketio/socket.io-redis#352]
Hi. How does a socket know where the room located? I mean `adapter.remoteJoin()` is used for joining a room on a remote node, while `socket.join()` is used for joining a room on local node. Is there any api for a socket to know about where the room is located (local or remote)?

**Comment by arunp0** [comment]
```
let sockid // socket id u want do disconnect
let client
client = io.sockets.connected[sockid]
if (!_.isNil(client)) {
    client.disconnect() // local
} else {
    io.of('/').adapter.remoteDisconnect(sockid, true, (error) => {})
}
```

**Comment by darrachequesne** [comment]
Hi! Sorry for the delay.

> How does a socket know where the room located?

I'm not sure that I totally understand the question. A room is not located on a particular instance. 

We have added a section about how the adapter works: https://github.com/socketio/socket.io-redis#how-does-it-work-under-the-hood

Is it clear enough?

**Comment by darrachequesne** [comment]
For future readers: please check https://socket.io/docs/v4/server-instance/#Utility-methods
