### ISSUE TITLE
How to retrieve socket(ws) from another nodes/pods

### ISSUE THREAD

**Issue by Manjukb** [socketio/socket.io-redis#353]
HI, is there anyway we can retrieve socket object across nodes/pods
need socket object(ws) to communicate with client but not able to get it 
we are facing  issue after scaling our nodejs to multiple pod

**Comment by arunp0** [comment]
You need to maintain the mapping between userId to socket Id
Whenever you want to communicate to any user, with socket Id found from the user mapping 
(You can use Redis to maintain this mapping)

```js
const io = require('socket.io')(3000);
const redisAdapter = require('socket.io-redis');
io.adapter(redisAdapter({ host: 'localhost', port: 6379 }));

let socketId = '' // userId => socketId mapping

let client = io.sockets.connected[socketId] // if socket is connected to the same process
if (!client) { // if socket is probably connected in other node
    client = io.to(socketId)
}
client.emit('msg', 'You can use client object to emit independently of its in the same node or another node')

```

**Comment by Manjukb** [comment]
so i use `socket.io-request` to pull data from socket client through http
so in an express API i need to find a specific socket object and communicate with it
here is the code

> var ioreq = require('socket.io-request');
let client = io.sockets.connected[socketId] // if socket is connected to the same process
if (!client) { // if socket is probably connected in other node
    client = io.to(socketId)
}
ioreq(client ).request(req.body.method, {body: req.body}).then(function(res) {
logger.info(res, 'success result ');
result.json(res);
});


when i pass client instance to I get `Callbacks are not supported when broadcasting` error from socket.io-request lib i was thinking that socket object what i pass is wrong ?? any idea ?? am i doing some mistake here ?

thanks a lot for your help

**Comment by Manjukb** [comment]
looks client returned by `client = io.to(socketId)` is not valid

**Comment by darrachequesne** [comment]
@Manjukb please see my answer there: https://github.com/socketio/socket.io-redis/issues/283#issuecomment-684478660

**Comment by darrachequesne** [comment]
For future readers: please check https://socket.io/docs/v4/server-instance/#Utility-methods
