### ISSUE TITLE
Error: [HPM] Missing "target" option

### ISSUE THREAD

**Issue by liamcharmer** [socketio/socket.io-redis#354]
Tried to enter in the redis adapter, and everytime I try it shows the following error: 

```(node:46001) UnhandledPromiseRejectionWarning: Error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"}```

**Comment by darrachequesne** [comment]
@liamcharmer this does not seem related to `socket.io-redis`. Could you please provide a way to reproduce?

From a quick [Google search](https://www.google.com/search?q=Missing+%22target%22+option), it might be related to the `http-proxy-middleware` module.
