### ISSUE TITLE
Socket in cluster custom hook or redis?

### ISSUE THREAD

**Issue by webdpro** [socketio/socket.io-redis#355]
Ok just going to put this out there first, this is not an issue, and I have tried to get answers from stack-overflow but have gotten no replies so I figured I would go to the source to see if, well maybe I can get confirmation here. 

This is a similar question to #353 , we have a clustered environment and want to get the users in a room. I understand we can get the sockets across the nodes but for us we use the sock to add variables like nickname and an ID so just the socket is not that helpful. 

I have read, re-read, and then read 353 and #283 numerous times and the best I can come up with is I must store this in redis and that's fine as its not too much re-work. 

We have went over the options from simple get / set to hget and set and eventually settled with using a redis 'list' as this seemed the best way to not have to serialize / deserialize each time and also avoid possible race conditions 

Senario: When user joins a room we create an array with their socket, nickname then push to the parsed redis response, stringify and place back in. 

What we do now is actually create a flat 'array' string like so  

```
        var userData = '{"socketID":"' + socket.id + '","nickName":"' + userNickName + '","aID":"' + userID + '"}';
        myRedis.rpush(room, userData);
```

This does pushes the array to the redis list and when we want to get the users in a room we call 

```
myRedis.lrange(room, 0,-1,function(err,results){
      results = "[" + results + "]"
      console.log(JSON.parse(results));
    });

```

Leaving the room just pop the element out of the list like so 

```
  var userData =  '{"socketID":"' + socket.id + '","nickName":"' + socket.nickname  + '","aID":"' + socket.aid + '"}';
            myRedis.lrem(room,1, userData);
```

By doing this we prevent a race condition with get / set as each item is just and item in the list. So the million dollar question is, does this seem like the right way of doing it? I tried the customcalls as pointed out in #283 but it did not have the expected result. 

Anyhow, sorry for this not being in the right place but just trying to get some answer to our questions.

Thanks!

**Comment by darrachequesne** [comment]
For future readers: please check https://socket.io/docs/v4/server-instance/#Utility-methods
