### ISSUE TITLE
Pros/Cons of using shared Redis client as pub/sub client?

### ISSUE THREAD

**Issue by Dumk0** [socketio/socket.io-redis#356]
Hello.

Can someone explain pros & cons using multiple Redis clients instead of one shared?
I have an application using Redis storage additionally to socket.io-redis package.
It means that every instance has 3 connections to the Redis DB.

There is an example in the repo README.md:

```
const redis = require('redis');
const redisAdapter = require('socket.io-redis');
const pub = redis.createClient(port, host, { auth_pass: "pwd" });
const sub = redis.createClient(port, host, { auth_pass: "pwd" });
io.adapter(redisAdapter({ pubClient: pub, subClient: sub }));
```

can I use the following solution:
```
const redis = require('redis');
const redisAdapter = require('socket.io-redis');
const redisClient = redis.createClient(port, host, { auth_pass: "pwd" }); // or take existing connection
io.adapter(redisAdapter({ pubClient: redisClient, subClient: redisClient }));
```

what is the (dis)advantage of doing so?

**Comment by darrachequesne** [comment]
I think using a shared client will not work, because the subscriber (`subClient`) is put in a special state:

From https://redis.io/commands/subscribe

> Once the client enters the subscribed state it is not supposed to issue any other commands, except for additional SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING and QUIT commands.

From https://github.com/NodeRedis/node-redis#pubsub:

> When a client issues a SUBSCRIBE or PSUBSCRIBE, that connection is put into a "subscriber" mode. At that point, the only valid commands are those that modify the subscription set, and quit (also ping on some redis versions). When the subscription set is empty, the connection is put back into regular mode.

**Comment by Dumk0** [comment]
Could find that info. Thanks for quick answer.
Closing the issue now.
