### ISSUE TITLE
Is it possible to emit to local sockets in a room only?

### ISSUE THREAD

**Issue by derikb** [socketio/socket.io-redis#358]
Trying to figure out if there is way to ONLY emit to the local sockets in a room.

Setup:
- I'm using multiple servers running socket.io with the redis adaptor to connect them.
- I'm also use redis pubsub to send events to socket.io from other non node/socket.io servers.
- The socket.io receives those events and emits information to rooms.

The problem is that when I publish to redis, all the socket.io servers receive the message and emit to all sockets in a room, which means the sockets all get the same message twice (since there are two servers).

So is there a way to have the server NOT use the adaptor in specific cases so the event only goes to the sockets connected to the specific server in a specific room?

**Comment by darrachequesne** [comment]
Yes, you can use the [local](https://socket.io/docs/v3/server-api/index.html#Flag-%E2%80%98local%E2%80%99) flag:

```js
io.local.emit('an event', { some: 'data' });
```

It will only broadcast to the sockets that are connected to the given server. (works in v2 and v3)
