### ISSUE TITLE
Error: timeout reached while waiting for clients response after  reconnection on new instant

### ISSUE THREAD

**Issue by Natashkinsasha** [socketio/socket.io-redis#365]
Hi. When one of instants crashed and socket reconnected to new instant. I try get clients in room where was 
reconnected socket, but I get Error: timeout reached while waiting for clients response. How I can decide this problem?

            io.of(namespace).in(roomId).clients((err: Error, clients: string[]) => {
                if (err) {
                    // Error: timeout reached while waiting for clients response
                }
                
            });

socket.io-redis: 5.4.0.

**Comment by darrachequesne** [comment]
Yes, that is expected. The `clients()` method waits for the response of N servers, but only N - 1 servers send an answer. The next call to `clients()` should be successful, so I think the error can be discarded.

**Comment by Natashkinsasha** [comment]
> Yes, that is expected. The `clients()` method waits for the response of N servers, but only N - 1 servers send an answer. The next call to `clients()` should be successful, so I think the error can be discarded.

In next version socket.io-redis for socket.io v3, is this problem solved?

**Comment by darrachequesne** [comment]
I'm going to close this, as I don't think there is something to fix. Please reopen if needed.
