### ISSUE TITLE
msgpack v5

### ISSUE THREAD

**Issue by hannesvdvreken** [socketio/socket.io-redis#37]
There's a new kid in town:

https://github.com/mcollina/msgpack5

Here's one reason to switch:

https://github.com/creationix/msgpack-js/commit/1e6feb3be0afe14deecd121d969d6c8d55adb2a0#commitcomment-8285013

**Comment by didaxRedux** [comment]
I agree!
I've also suggested a correction (see https://github.com/socketio/socket.io-redis/pull/105).
With old msgpack library errors occur on UInt64 conversion.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/pull/156.
