### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by drizzef** [socketio/socket.io-redis#375]
Hi, 
I'm getting error while try to send to specific room a message:
`TypeError: callback is not a function
    at Encoder.encode (/home/XXX/Projects/dorix/node_modules/socket.io-parser/index.js:135:5)
    at RedisAdapter.broadcast (/home/XXX/Projects/dorix/node_modules/socket.io-adapter/dist/index.js:102:45)
    at RedisAdapter.broadcast (/home/XXX/Projects/dorix/node_modules/socket.io-redis/dist/index.js:267:15)
    at Socket.emit (/home/XXX/Projects/dorix/node_modules/socket.io/lib/socket.js:171:18)
    at EventsGateway.handleLogin (/home/XXX/Projects/dorix/packages/hub/dist/events/events.gateway.js:28:43)
    at /home/XXX/Projects/dorix/packages/hub/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
    at process._tickCallback (internal/process/next_tick.js:68:7)
`
the code the throw the error:
`socket.to(payload.parentBranchId).emit('incoming_order', 'dee');`

**Comment by darrachequesne** [comment]
Which version are you using? Please see https://github.com/socketio/socket.io-redis#compatibility-table

**Comment by 2tick** [comment]
I have the same issue. I tested my package version also.. please help me..

**Comment by 2tick** [comment]
Hello,
it works on
socket.io = 2.4.1
socket.io-redis = 5.4.0

but not works on latest versions (socket.io > 3.0.0 and socket.io-redis > 6.0.0)
please help me...

**Comment by TheBrown** [comment]
I'm also facing with the latest version of socket.io and socket.io-redis it response callback is not a function

**Comment by darrachequesne** [comment]
@drizzef based on the stacktrace you provided, it seems there is a mismatch between:
- the version of `socket.io-parser`: no dist (`node_modules/socket.io-parser/index.js`), which would mean no TypeScript (Socket.IO v2)
- the version of `socket.io-adapter`: with dist (`node_modules/socket.io-adapter/dist/index.js`), which would mean with TypeScript (Socket.IO v3)

Could you please check in your dependency tree? The compatibility should be something like

- `socket.io@2 / socket.io-redis@5 / socket.io-adapter@1 / socket.io-parser@3`
- `socket.io@3 / socket.io-redis@6 / socket.io-adapter@2 / socket.io-parser@4`

**Comment by mkj-git** [comment]
I also faced the same issue. Installing the matched version from https://github.com/socketio/socket.io-redis#compatibility-table fixed it

**Comment by darrachequesne** [comment]
I guess we can close this issue then.

For future readers, please check the compatibility table [here](https://github.com/socketio/socket.io-redis#compatibility-table).

**Comment by giovanni-bertoncelli** [comment]
@darrachequesne in order to install versions under 7 I have to use the deprecated npm package `socket.io-redis` instead of the new `@socket.io/redis-adapter`? Do you confirm this?

**Comment by darrachequesne** [comment]
@giovanni-bertoncelli yes, that's right :+1:
