### ISSUE TITLE
async sockets functions should return immediately on getNumSub === 0

### ISSUE THREAD

**Issue by fliespl** [socketio/socket.io-redis#376]
```
public async sockets(rooms: Set<Room>): Promise<Set<SocketId>> {
}
```

It's possible for getNumSub to return 0. In this case no response will be received and adapter will fail with error.

This could happen in situation where you have only one server active (i.e. all others are down) and want to immediately get clients list (and redis is not ready yet).

It will end with "timeout reached while waiting for clients response".

Sample repro:
```
const server = require('http').createServer();
const redisAdapter = require('socket.io-redis')(process.env.REDIS_DSN);
const io = require('socket.io')(server, {
    serveClient: false,
    pingInterval: 10000,
    pingTimeout: 5000,
    cookie: false
});
io.adapter(redisAdapter);
io.listen(3000);
io.sockets.adapter.clients(function (err, clients) {
    console.log(err, clients);
});
```

This can be of course fixed by doing it this way:

```
// wait for redis to connect
setTimeout(function() {
    io.sockets.adapter.clients(function (err, clients) {
        console.log(err, clients);
    });
}, 1000);
```

but I guess it should be handled cleanly in library.

I guess the best resolution would be that sockets resolve promise immediately when getNumSub === 0.

**Comment by darrachequesne** [comment]
Yes, that makes sense. Could you please open a PR with that fix?

Thinking about it, I guess we could also handle the case when getNumSub returns 1 (that should not be a common case though).

**Comment by fliespl** [comment]
PR ready #378

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-redis/commit/6c8d7701962bee4acf83568f8e998876d3549fb8.
