### ISSUE TITLE
Create manual connection for sid from another node instance

### ISSUE THREAD

**Issue by DisaPadla** [socketio/socket.io-redis#379]
Hi, I have a question. I have two instances of the server. I have several socket connections. Imagine, one instance dies. After that new instance get up. Look at the client side, I don't get messages from the new instance. I get new messages only after refresh the page and create a new socket connection.  How can I take sids from another instance and create a manual connection on the new instance?

**Comment by darrachequesne** [comment]
Hi! I'm not sure I understand your issue.

> Imagine, one instance dies. After that new instance get up.

In that case, the client should automatically reconnect to the other instance (but with another ID, since it's a new connection). Isn't that the case?

**Comment by DisaPadla** [comment]
@darrachequesne  i found this [issue](https://github.com/socketio/socket.io-redis/issues/203). Looks like I have the same problem

**Comment by DisaPadla** [comment]
I try to describe a problem with more details. When node instance is running, the server creates RabbitMQ connection instance and uses it in socket connections. I get some messages from RabbitMQ from other services. I have two node instances. RabbitMQ pushes the first message to the first node instance and push the second message to another node instance. Socket connection takes these messages and creates room (looks like ```task-{useId}```) and push messages to the client. When some of node instance dies, we brought up a new instance. The new instance also create RabbitMQ connection. We get messages from Rabbit to our new instance but not push them to the client. Looks like room ```task-{useId}``` doesn't exist on the new node instance

**Comment by darrachequesne** [comment]
Hi! Did you find a solution?

**Comment by DisaPadla** [comment]
Yeah. Thanks
