### ISSUE TITLE
Adapter functions are undefined

### ISSUE THREAD

**Issue by djllap** [socketio/socket.io-redis#380]
I'm trying to set up socket.io-redis for a kubernetes deployment, but something is wrong with the configuration. It is partially working, in that I can see socket.io messages in redis using redis-cli PSUBSCRIBE, but I don't have access to any of socket.io-redis' functions.

```io.of('/').adapter.sockets()```, ```io.of('/').adapter.allRooms()``` and every other function that should be available upon the successful configuration of socket.io-redis is undefined. My configuration is below.
```
const app = require('express')();
const server = require('http').createServer(app);
const io = require('socket.io')(server, {transports: ['websocket']});
const redisAdapter = require('socket.io-redis');
io.adapter(redisAdapter({port: 6379, host: '127.0.0.1'}));
```

Redis PSUBSCRIBE logs
```
1) "pmessage"
2) "*socket.io*"
3) "socket.io#/#"
4) "\x93\xa6MLcXhU\x83\xa4type\x02\xa4data\x92\xa4test\xactest data 66\xa3nsp\xa1/\x82\xa5rooms\x90\xa5flags\x80"
```
 I am using socket.io 2.3.0 and socket.io-redis 5.4.0 which should be compatible according to the docs. Node version is v14.2.0.

**Comment by darrachequesne** [comment]
RedisAdapter.clients() was renamed to RedisAdapter.sockets() in the [6.0.0](https://github.com/socketio/socket.io-redis/releases/tag/6.0.0) release.

Please see [here](https://github.com/socketio/socket.io-redis/tree/5.4.0) for the documentation of the `5.4.0` version.

**Comment by djllap** [comment]
Yeah, that's it. It just never occurred to me that the entire api would be different across versions. Thanks for your help!
