### ISSUE TITLE
Not Working Socket.IO.emit() in socket.redis-io version 6.0.1

### ISSUE THREAD

**Issue by sinwoo1225** [socketio/socket.io-redis#382]
```
import socketIo from "socket.io";
import redis from "socket.io-redis";

io.adapter(redis({ host: REDIS_MASTER_HOST, port: Number(REDIS_MASTER_PORT) }));

socket.on("sendMessage", async ({ message, userId, roomId }) => {
		try {
			socket
				.to(`room_${roomId}`)
				.emit("sendMessage", { ...response.dataValues }); // ❗ Error
		} catch (error) {
			console.log("❌", error);
		}
	});

```

In `socket.io-redis` version 6.0.1, `socket.io.emit()` is not working
but In version 5.2.0, `socket.io.emit()` is working!!!

So, I submit this issue

**Comment by darrachequesne** [comment]
Which version of Socket.IO are you using? You will find the compatibility table here: https://github.com/socketio/socket.io-redis#compatibility-table

**Comment by sinwoo1225** [comment]
> Which version of Socket.IO are you using? You will find the compatibility table here: https://github.com/socketio/socket.io-redis#compatibility-table
Oh, I understand that my problem is compatibility issue! 
I use socket.io 2.x.x version and socket.io-redis 6.0.1 😂😂😂
Thank you
