### ISSUE TITLE
Feature request: extend from custom adapter

### ISSUE THREAD

**Issue by sebamarynissen** [socketio/socket.io-redis#383]
I have a use case we're I have a custom adapter that extends from the default socket.io in memory adapter that I would like to use in combination with `socket.io-redis`. It's possible to add this functionality with full backwards compatibility as follows:
```js
import { Adapter } from 'socket.io-adapter';

export function extendFrom(BaseAdapter) {
  return class RedisAdapter extends BaseAdapter {
    // No other changes to the code required.
  };
}

export const RedisAdapter = extendFrom(Adapter);
```

I will try to file a PR for this, but I have no experience in TypeScript and my first attempts won't compile.

**Comment by darrachequesne** [comment]
I think we can now close this, as https://github.com/socketio/socket.io-adapter/issues/66 was merged.
