### ISSUE TITLE
clientRooms method completely gone after major update?

### ISSUE THREAD

**Issue by ungoldman** [socketio/socket.io-redis#385]
Hello, I'm in the process of upgrading a complex production deployment to socket.io v3 & socket.io-redis v6.

I just noticed the `RedisAdapter.clientRooms` method we were using up until now is just plain gone. I assumed it would be renamed similarly to `RedisAdapter.clients` -> `RedisAdapter.sockets`, resulting in a `RedisAdapter.socketRooms` method, but it looks like it was removed from this library altogether.

The removal of this method is not mentioned in the [CHANGELOG](https://github.com/socketio/socket.io-redis/blob/master/CHANGELOG.md#600-2020-11-12), I found it by looking at the actual diff -- https://github.com/socketio/socket.io-redis/compare/5.4.0...6.0.0.

Any chance of this method coming back in some form? Was there a reason it was removed? If it's not coming back, can we add a note in the change log so other users who were relying on this method will know that it's not there anymore?

**Comment by darrachequesne** [comment]
We have added some utility methods in Socket.IO v4 (the major bump is due to a minor breaking change and should not impact most users).

The `fetchSockets` method can be used as a replacement for `clientRooms`:

```js
const sockets = await io.in(theSocketId).fetchSockets();
if (sockets.length) {
  console.log(sockets[0].rooms);
}
```

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Additional-utility-methods

Does it suit your use case?

**Comment by ungoldman** [comment]
We found a workaround but I believe the above would be an acceptable substitute. Please document in the changelog that `clientRooms` was removed for future users if you haven't already! Thank you for all your work.

**Comment by kor3k** [comment]
i'm having the same issua, but `fetchSockets()` approach does not work. 

```
const sockets = await io.in(theSocketId).fetchSockets();
if (sockets.length) {
  sockets[0].join('aaa');
  console.log(sockets[0].rooms);
}
```

always returns an empty Set.

**Comment by darrachequesne** [comment]
The changelog was updated here: https://github.com/socketio/socket.io-redis/releases/tag/6.0.0
