### ISSUE TITLE
some rooms are not cleared

### ISSUE THREAD

**Issue by yanush** [socketio/socket.io-redis#386]
I have an admin console in which I call periodically:
`this.io.of('/').adapter.allRooms()`
It seems that some of the rooms are not being cleared even though they have no users
Is it a memory leak, or am I missing some socket.io cleanup that needs to be done when all players have left the room?

**Comment by DavraYoung** [comment]
Try to look at code in Base socket.io-adapter. Maybe the problem is there:
https://github.com/socketio/socket.io-adapter/blob/c95ab42aeffc6640268aa4f20c15ede2915f5cf2/lib/index.ts#L72

**Comment by darrachequesne** [comment]
That's weird, the rooms must be cleaned up once there is no more socket instances in it.

Are you able to reproduce? Could you please share some code?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
