### ISSUE TITLE
Question: should new Redis cluster instances be created for the adapter or can an existing one be used?

### ISSUE THREAD

**Issue by marnixhoh** [socketio/socket.io-redis#387]
Hi,

I am already using a Redis cluster client (ioRedis). My question is, if I should pass this to socket.io-redis or if I should create new clients. In other words, should I use this:

```
// the client I was already using
const redis = new Redis.Cluster(startupNodes)

const ioAdapter = redisAdapter({
    pubClient: redis,
    subClient: redis
})
```

or this:

```
// the client I was already using
const redis = new Redis.Cluster(startupNodes)

const ioAdapter = redisAdapter({
    pubClient: new Redis.Cluster(startupNodes),
    subClient: new Redis.Cluster(startupNodes)
})
```

I have really tried to find an answer myself, but I just can't figure out what the consequences of using either method would be.

Thank you so much

**Comment by darrachequesne** [comment]
You can reuse the same client as the `pubClient`, but you need to provide a distinct Redis client as the `subClient`:

> Once the client enters the subscribed state it is not supposed to issue any other commands, except for additional SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING, RESET and QUIT commands.

From: https://redis.io/commands/subscribe

So, in your case:

```js
// the client I was already using
const redis = new Redis.Cluster(startupNodes)

const ioAdapter = redisAdapter({
    pubClient: redis,
    subClient: new Redis.Cluster(startupNodes)
})
```

**Comment by marnixhoh** [comment]
@darrachequesne Thank you sooo much for your answer!! This is exactly what I was looking for :)
