### ISSUE TITLE
Socket.io v3 Server compatible with v2 clients

### ISSUE THREAD

**Issue by motawy** [socketio/socket.io-redis#388]
As of Socket.IO 3.1.0, the v3 server is now able to communicate with v2 clients.

Is this library compatible using server v3 -> client v2?

**Comment by darrachequesne** [comment]
Yes it is!

Note: server v2 + `socket.io-redis@5` is also compatible with server v3 + `socket.io-redis@6`

Documentation: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#How-to-upgrade-an-existing-production-deployment
