### ISSUE TITLE
What happens if Redis is down?

### ISSUE THREAD

**Issue by HayDegha0917** [socketio/socket.io-redis#393]
In AWS, the Redis service (Elasticache) has required maintenance windows that typically last 30 minutes. Our operations schedule is based on time on Mars and other factors and, consequently, moves around. It is possible, therefore, that Redis may be in maintenance at the time our Socket.IO server is in use. 

Our plan is to minimize the outage by setting up a Redis cluster with an additional read replica (see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Replication.Redis.Groups.html#Replication.Redis.Groups.Classic) and add retry logic in our code. With this change, if the primary Redis node is undergoing maintenance, the software will automatically fail over to the read replica.

The question is: Given all the above, what Socket.IO functionality is impacted?

Consider the following use cases:

- A client is subscribed and an event needs to be published to the client. I am hoping this will work because Redis does not need to be updated.
- A client wants to subscribe. Will this work? Will it work in some kind of degraded mode (_e.g.,_ maybe the subscription information is only held in memory)?
- A client wants to unsubscribe. What happens in this case?

**Comment by darrachequesne** [comment]
The Socket.IO Redis adapter only relies on Redis pub/sub mechanism.

So if the connection to Redis is cut, the messages will not be broadcasted anymore.

![image](https://user-images.githubusercontent.com/13031701/112638278-5e3be700-8e3f-11eb-8ef0-e562d8a4bc5c.png)

Regarding your use cases:

> - A client is subscribed and an event needs to be published to the client

This may unfortunately not work if the connection to Redis is down.

> - A client wants to subscribe
> - A client wants to unsubscribe

If by subscribe/unsuscribe you mean join/leave in Socket.IO terms, yes this will work, as they are stored in memory.

Please also see: https://github.com/socketio/socket.io-redis#how-does-it-work-under-the-hood

**Comment by HayDegha0917** [comment]
@darrachequesne thank you for your reply. It was very helpful. This has a few implications. Please correct me if I'm wrong (I'm using your notation):

- If Server B crashes due to a fault and is then restarted, its clients will have to re-subscribe. If the client is using the Socker.IO client library, this will happen automatically. But if they are using a different client library, this may not be the case.

- In your diagram, if Redis is not available and an event is generated on Server A, Server B will not publish the event to its subscribed clients, but Server A **will** publish the event to its subscribed clients.

- If Redis is set up as a cluster, with one active node and one read-only node, and the active node is not available, the cluster will fail over to the read-only node (this presupposes that we have injected into `socket.io-redis` a Redis client that is able to handle the failover). The question is whether, in that case, pub/sub will still work. Any idea? (I suppose it's really a Redis question, but maybe you know?

**Comment by darrachequesne** [comment]
> If Server B crashes due to a fault and is then restarted, its clients will have to re-subscribe. If the client is using the Socker.IO client library, this will happen automatically. But if they are using a different client library, this may not be the case.

If by subscribe/unsuscribe you mean join/leave, no you will have to do it yourself. But the client will reconnect though.

> In your diagram, if Redis is not available and an event is generated on Server A, Server B will not publish the event to its subscribed clients, but Server A will publish the event to its subscribed clients.

Yes :+1: 

> If Redis is set up as a cluster, with one active node and one read-only node, and the active node is not available, the cluster will fail over to the read-only node (this presupposes that we have injected into socket.io-redis a Redis client that is able to handle the failover). The question is whether, in that case, pub/sub will still work. Any idea? (I suppose it's really a Redis question, but maybe you know the answer?)

I think the best way is to manually test the failover.

**Comment by HayDegha0917** [comment]
Thanks for the info and for confirming my understanding.
