### ISSUE TITLE
socket.client.writeToEngine is not a function error

### ISSUE THREAD

**Issue by jzombie** [socketio/socket.io-redis#402]
Originally discovered this issue without having upgraded anything and being on socket.io 3.1.2 / socket.io-redis 6.0.1 for a while.

Tried upgrading to latest and issue is still apparent.  It happens when I call io.emit(...)

Was able to circumvent the issue for now by just iterating through all of the sockets and sending the event I need.

![writeToEngine](https://user-images.githubusercontent.com/1139657/117730833-0670f980-b1bb-11eb-8f44-077cf4e76679.png)

**Comment by jzombie** [comment]
Disregard.  After patching everything to latest once again, it seems to be working as expected now.  Must have missed something before.

**Comment by jitbasemartin** [comment]
I have the same issue, which versions are you using to fix the problem ?

**Comment by jzombie** [comment]
I had upgraded to 4.0.2 twice (server and client), the first time unsuccessfully (was still running into same issue), then deleted node_modules and package.lock (might not need to delete package.lock), and tried again, and it was successful.

I'm assuming the latest version would be the same.

My conclusion is that some upstream dependency somehow got shifted and wasn't sticky after all.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-redis-adapter/commit/f2265bafa26d03fd428f63fcc7df597d565cf9fb.

`socket.io-redis@6.1.0` could include `socket.io-adapter@2.3.0`, which uses the `
socket.client.writeToEngine()` method that was added in `socket.io@4.1.0`. Sorry for the mess!
