### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by peteruithoven** [socketio/socket.io-redis#41]
I'm developing a project where we have multiple Node.js instances and we use *socket.io-redis* to broadcast to all clients of all instances. This works but it seems to consume lot's of CPU. 
I've done a couple of tests:
- When I start 4 instances and I broadcast messages in all instances the cpu of all go to 100%. 
- When I start 4 instances and I broadcast messages in 1 instance the cpu of that instance is 1 to 3% and all the other instances use 100%. 
- When I don't use socket.io-redis, start 4 instances and broadcast messages in 1 instance the cpu of that instance is 1 to 3% and all the others are 0%. 

I'm using a "stresstest" where I create 100 namespaces with each 2 clients and where one client broadcasts something to the other client, every second (with {state: 'mystate'} as data).
(I'm using PM2 to start multiple instances and it's monitor functionality to monitor the cpu)
I've used the debug module to see what's going on on the other instances when I use socket.io-redis and I see it's basicly lot's of `socket.io-redis ignore different namespace`. 

I think socket.io-redis isn't optimized for "lot's" of namespaces?

**Comment by objectiveSee** [comment]
This issue has been resolved in version `1.0.0`, which includes #46 as mentioned in the comment above.
