### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by hekike** [socketio/socket.io-redis#64]
I see that this repository contains bunch of unreleased changes.
When do you plan to release it?

**Comment by danpe** [comment]
:+1:

**Comment by flohdot** [comment]
:+1:

**Comment by guybe1977** [comment]
:+1:

**Comment by akashkrishnan** [comment]
:+1:

**Comment by Climax777** [comment]
+1

**Comment by bf** [comment]
+1

**Comment by artofspeed** [comment]
+1

**Comment by manuelfc1** [comment]
+1

**Comment by mscdex** [comment]
@rauchg Any chance to publish a new version to npm?

**Comment by mavrick** [comment]
bump

**Comment by barisusakli** [comment]
A new release would be nice since 0.1.4 doesn't work with 2.3.1 of node_redis

**Comment by nkzawa** [comment]
We are working for the new release.

**Comment by japrescott** [comment]
happy to hear :)

**Comment by irakliy81** [comment]
+1

**Comment by m14t** [comment]
@nkzawa Thanks for the `0.2.0` release.  Would it be possible to update NPM with this version.

Currently https://www.npmjs.com/package/socket.io-redis is still showing `0.1.4` as the latest release.

**Comment by toblerpwn** [comment]
@m14t - looks like this was done at some stage :)

also, if you use `socket.io-emitter`, be sure to update that to `0.3.0` to avoid a breaking change.
