### ISSUE TITLE
Support Redis UNIX domain sockets

### ISSUE THREAD

**Issue by ilkkao** [socketio/socket.io-redis#67]
Please revert this commit which removes the Redis UNIX domain socket support: 

https://github.com/Automattic/socket.io-redis/commit/f49d9f8c9ec0a8eeed9dad3a62e59d1105389b72

Background: Redis server can be accessed in two ways. 

1) via TCP connection, you need to know Redis hostname/IP address and port.
2) via UNIX domain socket, this is a special file and you need to know the path to it. Works only when client and server are located on the same host.

Multiple clients can use the same UNIX domain socket file at the same time. Comment in the revert indicates that there must be a some sort of misunderstanding about that.

I have a cluster with 10 workers handling socket.io connections at the same time. I'd like to use this library to make them to work together. I prefer to use UNIX domain sockets instead of local TCP connections because UNIX domain socket provide a better performance on Linux as they bypass the TCP/IP stack.

@rauchg

**Comment by ilkkao** [comment]
Just to clarify. There's no difference between

``
var pub = redis.createClient(1234, 'localhost');
var sub = redis.createClient(1234, 'localhost');
```
and
```
var pub = redis.createClient('/tmp/redis.sock');
var sub = redis.createClient('/tmp/redis.sock');
```

both create two connections.

**Comment by nkzawa** [comment]
You can just pass custom pub/sub clients in this case.

```js
var pub = redis('/tmp/redis.sock');
var sub = redis('/tmp/redis.sock');
io.adapter(adapter({ pubClient: pub, subClient: sub }));
```
