### ISSUE TITLE
Handling client messages in other nodes

### ISSUE THREAD

**Issue by Levino** [socketio/socket.io-redis#70]
Hey everyone,

I am sorry but I cannot get my head wrapped around it.

What I want to do is to have one node (or one class of nodes) A that is handling client to server connections. All messages that clients send to node A should be kinda "dumped" in to the redis database where node (class) B is listening on message of type "X" and if it sees any, does stuff.

Does anyone have a basic example on how to achieve this? Especially a way to create a Socket.IO service that is not listening to the outside world but only to redis and gets messages from other nodes is what I cannot achieve to implement.

Thanks in advance

Levin

**Comment by peteruithoven** [comment]
@Levino Does this node (class) B is a seperate Node.js instance? Then you could probably use Redis pub/sub. See for example: https://www.npmjs.com/search?q=redis%20pub%20sub

If it's on the same instance you can just implement a event system? No need for socket.io or Redis then. 

Not sure socket.io-redis is relevant for your problem.

**Comment by reqshark** [comment]
@Levino, here's some examples:

### rabbitMQ
https://github.com/squaremo/rabbit.js/blob/master/example/easyamqp/server.js

### zmq
https://github.com/JustinTulloss/zeromq.node/tree/master/examples

### axon
https://github.com/tj/axon/tree/master/examples/pubsub

### nanomsg
https://github.com/nickdesaulniers/node-nanomsg/blob/master/examples/pubsub.js

nanomsg offers about an order of magnitude higher TCP (a.k.a RPC) performance when compared with node's net module ([used in axon](https://github.com/tj/axon/blob/master/lib/sockets/sock.js#L364)) and nanomsg is either equitable or may be [slightly more performant than zmq](https://twitter.com/rekshark/status/571078445444284416)... <-- that links to a test result only looking at latency for small msg envelopes. 

granted, zmq and nanomsg offer comparable performance to redis pub/sub or rabbitMQ at small scale.  for larger scale operations, like over 50K connections, these scenarios will generally favor zmq or nanomsg in terms of msg delivery and protocol reliability when looked at on equal systems and under similar network conditions. At that point the performance bottleneck is actually Node.js. Why? Zeromq and nanomsg topologies tend to use fewer resources by virtue of deliberate reductions in the ratio of kernel space to user space interactions. Engineering for performance is the heart of msg queue work. 

You may be interested in testing these modules by examining endpoint-to-endpoint transport limits using benchmarks framework setups I've started here: https://github.com/reqshark/perf you could easily plug in redis or any other MQ pub/sub style backend and observe the results to determine the most appropriate module for your specific needs or the needs of devices connected to your network.

performance is only part of it (the simplicity and nature of the implementation patterns are the other part), but generally for smaller msgs (under 500kB) nanomsg offers the lowest latency, and highest throughput backend TCP pub-sub pattern if you want to use node.js.  As msgs grow in size toward 1MB, node-zmq may exhibit better overall system performance than the node-nanomsg module. You can tune nanomsg sockets using options in the API to meet zmq module performance, however, at that point it's not the default.

once you understand the sort of patterns that MQ systems offer, you'll see they're all kinda the same. Probably the best place to get started learning about these patterns is the zeromq guide:

http://zguide.zeromq.org/page:all

**Comment by Levino** [comment]
@reqshark Okay. Thanks a lot for this in depth explanation. I meanwhile implemented it with "kue". As I am merely passing on messages, this seems quite of an overhead to me, but so far it works fine.
