### ISSUE TITLE
Cannot read split of undefined, and trailing bytes

### ISSUE THREAD

**Issue by zacharynevin** [socketio/socket.io-redis#72]
I have the following package versions:
````
{
    "redis": "2.0.1",
    "socket.io": "1.3.7",
    "socket.io-emitter": "0.2.0",
    "socket.io-redis": "0.1.4",
}
````
My redis version is 2.8.21.

When I instantiate `socket.io-redis` with `return_buffers` set to true for the clients, I get the following error: 

`channel.split("#") <!-- cannot read split of undefined`

If I monkey patch the code in `index.js` for `socket.io-redis` so that the channel is a string, I get a trailing bytes error. Additionally, when I downgrade redis to `1.0.0`, I get a trailing bytes error.

I can deal with downgrading redis to `1.0.0`. However, no permutation of `socket.io-redis`, `socket.io-emitter`, and `redis` seems to ever solve the trailing bytes error. This is a very critical issue for me. Is there an initiative to fix it in the very near future?

**Comment by aPoCoMiLogin** [comment]
Yes there is already fix for it, but is not tagged, so there is no package for it on npmjs. https://github.com/socketio/socket.io-redis/issues/73#issuecomment-158613469 there is some workaround for it.
