### ISSUE TITLE
TypeError: channel.split is not a function

### ISSUE THREAD

**Issue by serohh** [socketio/socket.io-redis#73]
in index.js,

var pieces = channel.split('#');      change this bit of code into this
var pieces = channel.toString().split('#');

and it works.

**Comment by noamtz** [comment]
I'm using socket.io-redis 0.1.4 and i'm getting the same error to.

**Comment by barisusakli** [comment]
Looks like it was fixed but never published 

https://github.com/socketio/socket.io-redis/commit/c07b3bdaef579fbe963170b9ad490b656d31494c#diff-168726dbe96b3ce427e7fedce31bb0bc

@rauchg

**Comment by aPoCoMiLogin** [comment]
@noamtz, @sgarbesi  Well latest changes are not tagged, so if you want latest fixes you have to provide `socketio/socket.io-redis#master` or `socketio/socket.io-redis#7d7814920ed57c9c500a56be019e893413279b75` instead of version, then you'll get it fixed.

package.json:

```"socket.io-redis": "socketio/socket.io-redis#master"```

**Comment by irakliy81** [comment]
the above fix works - but is there a plan to tag the latest changes as an actual release? Thanks!

**Comment by rauchg** [comment]
Yep. A big release of `socket.io-redis` is coming in the next week.

**Comment by aPoCoMiLogin** [comment]
Sounds good, will test it later, now have to stick to that workaround.

**Comment by jdegger** [comment]
@rauchg Any news on when you're going to release?

**Comment by aPoCoMiLogin** [comment]
@jdegger even if they release latest changes, there are still issues which probalby you will face it: https://github.com/socketio/socket.io-redis/issues/78 just use version 0.1.3

**Comment by jdegger** [comment]
Alright thanks for letting me know @aPoCoMiLogin
