### ISSUE TITLE
New maintainer for this project

### ISSUE THREAD

**Issue by GeorgeSapkin** [socketio/socket.io-redis#75]
This is obviously a very popular, useful and important part of Socket.IO which has not been maintained for a while. Has Socket.IO considered appointing a new maintainer? It's a big hassle finding a combination of fixes from all the forks right now.

**Comment by shnist** [comment]
+1

**Comment by jdesboeufs** [comment]
+1

**Comment by Michael77** [comment]
+1

**Comment by nulliel** [comment]
+1

**Comment by japrescott** [comment]
+1

**Comment by irakliy81** [comment]
+1

**Comment by aPoCoMiLogin** [comment]
+1

**Comment by jdesboeufs** [comment]
Today an alternative solution is to use https://github.com/primus/primus which is well maintained and provide an interesting abstraction layer, with Redis support (official plugin).

**Comment by Bretto** [comment]
+1

**Comment by robbennet** [comment]
+1

**Comment by artofspeed** [comment]
+1

**Comment by Buinskii** [comment]
+1

**Comment by hgcummings** [comment]
Any chance of a response on this from the existing maintainers? @rauchg?

If the project could do with some help I'd be happy to volunteer.

**Comment by rauchg** [comment]
@hgcummings I'm planning a release for the coming week. Apologize for the delay.

**Comment by hgcummings** [comment]
Thanks for the update @rauchg.

Note that I wasn't just commenting because I'm impatient for a release. The offer still stands if you could use any help in the future.

**Comment by jdesboeufs** [comment]
Thanks @rauchg.

But I agree with @hgcummings: this project is important for many people, you'd better promote some additional maintainers.

**Comment by hgcummings** [comment]
@rauchg any update on the release?

**Comment by rauchg** [comment]
@jdesboeufs @hgcummings would any of you two be down for helping coordinate the next release? I believe this also requires that we push new client and server due to the changes of namespace handling.

**Comment by hgcummings** [comment]
Hi @rauchg. Yes, I'd be happy to help out. Just let me know what you need.

**Comment by ryoqun** [comment]
+1

**Comment by hgcummings** [comment]
@rauchg do you know when you'll be able to spend time on this? Let me know if there's anything I can do to help.
