### ISSUE TITLE
How to get all clients in a room, or all rooms a client is in?

### ISSUE THREAD

**Issue by artofspeed** [socketio/socket.io-redis#83]
Is there a way to do this across multiple node processes in the recent v1.0 release?

I saw this was a very requested feature. Is there a chance this gets implemented in a the near future? If not, has anyone succeeded in simulating this functionality based on the current 1.0 version?

Thanks!

**Comment by robbennet** [comment]
This is as close as it gets currently

https://github.com/socketio/socket.io-redis/pull/15

**Comment by darrachequesne** [comment]
Now available in v1.1.0 with https://github.com/socketio/socket.io-redis/pull/109
