### ISSUE TITLE
Using pubClient/subClient for other things than socket.io-redis

### ISSUE THREAD

**Issue by andreialecu** [socketio/socket.io-redis#90]
I'd like to be able to use pubClient/subClient for other tasks in my app without needing to create new redis connections.

This seems possible. except that the `onmessage` handler in this library seems to process every message anyway, not just the ones that are meant for it.

It seems like an easy fix, just need to check if `channel` matches any of the adapter's known subscribed channels.

Would you be interested in a PR for this?

**Comment by objectiveSee** [comment]
@andreialecu We create new Pub/Sub clients for your non-socket.io related messaging. Redis can handle a lot of clients (perhaps 100k) so it's likely that the same solution will work for you.

**Comment by andreialecu** [comment]
Cloud redis providers limit the number of connections in their plans... unlimited is a higher tier usually. Also it seems like a waste of resources when it can be so easily reused.

**Comment by objectiveSee** [comment]
Giving socket.io-redis it's own clients on costs two extra redis clients. Is that really an issue for your cloud provider?

**Comment by andreialecu** [comment]
It's two clients per node. So for 10 nodes that is 40 connections instead of 20.

**Comment by objectiveSee** [comment]
I understand you point. Currently the `onmessage` function checks for a namespace to the packet. If there is no namespace then the sub client returns and doesn't process the message any more. Is that adequate for your needs? (ie. don't use a namespace `nsp` on other messages that are not intended for socket.io-redis)

```js
  Redis.prototype.onmessage = function(channel, msg){
    var args = msgpack.decode(msg);
    var packet;

    if (uid == args.shift()) return debug('ignore same uid');

    packet = args[0];

    if (packet && packet.nsp === undefined) {
      packet.nsp = '/';
    }

    if (!packet || packet.nsp != this.nsp.name) {
      return debug('ignore different namespace');
    }

    args.push(true);

    this.broadcast.apply(this, args);
  };
```

**Comment by andreialecu** [comment]
The implementation tries to use msgpack.decode on every message regardless of its channel. The channel itself is never even checked. Messages that are not valid msgpack encoded messages, like anything custom on unrelated channels would likely result in errors being thrown.

**Comment by objectiveSee** [comment]
Hopefully one of the contributors can chime in here with their thoughts. It will be some sort of a performance hit to check the channel each time. Perhaps something like:

```js
  function Redis(nsp){
    Adapter.call(this, nsp);

    this.uid = uid;
    this.prefix = prefix;
    this.pubClient = pub;
    this.subClient = sub;

    var self = this;
    sub.subscribe(prefix + '#' + nsp.name + '#', function(err){
      if (err) self.emit('error', err);
    });
    if ( this.check_channel_name_first ) {
      sub.on('message', this.onmessage_channelCheck.bind(this));    	
    }  else {
      sub.on('message', this.onmessage.bind(this));
    }
  }

  Redis.prototype.onmessage_channelCheck = function(channel, msg){
    if ( /* channel is not being subscribed to */ ) {
      return;
    }
    return this.onmessage(channel, msg)
}
```

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/pull/107
