### ISSUE TITLE
Autodetect when redis clients are provided without return_buffers: true

### ISSUE THREAD

**Issue by calzoneman** [socketio/socket.io-redis#91]
The documentation states "If you supply clients, make sure you initialized them with the `return_buffers` option set to `true`."  Is it possible to auto detect this and warn/throw an error?

It would be a lot more friendly to fail up front with a helpful error message than blindly accept a badly configured redis client and cause cryptic errors such as in #38, #88.

**Comment by objectiveSee** [comment]
Makes sense to me. Adding the check would be simple, but I am not sure whether it is better to throw an error or perhaps send an error event. I am also not sure if both the pub and sub clients need this, or only sub. Currently if no client is provided the module will only set `return_buffers:true` for the sub client. The documentation should be updated to be more specific about whether the pub client also needs `return_buffers`. 

Here's how to add the check for the return_buffers:
```js
  // init clients if needed
  if (!pub) pub = redis(port, host);
  if (!sub) sub = redis(port, host, { return_buffers: true });

  // Add code here to detect if sub client was not initalized with return_buffers. What to do though?
  if (  !sub.options.return_buffers ) {

  }
```

**Comment by xyzlast** [comment]
Plz. check this issue. #17, #88  

I think return_buffers/detect_buffers issue is critical.

**Comment by calzoneman** [comment]
I just got tricked by this again today.  It looks like indeed only the sub client needs to have `return_buffers` set to `true`.

**Comment by darrachequesne** [comment]
Maybe
```
if (!sub.options.return_buffers) {
  throw new Error('I guess you should have read the manual!');
}
```
would be sufficient? :smile: 

PR is welcome!

**Comment by darrachequesne** [comment]
On second thought, how about defaulting to `messageBuffer` instead of `message` for the `subEvent`? That way, `return_buffers` flag should not even be needed.

https://github.com/luin/ioredis/blob/ea6fbf2f999774e085fb5a78b84993587839ae9c/lib/redis/parser.js#L112
https://github.com/NodeRedis/node_redis/blob/39c88206caa8807d7a601c095d3ad60cd31a5a17/index.js#L772

**Comment by calzoneman** [comment]
I think using `messageBuffer` is a better solution since it encapsulates the implementation detail of processing buffers in `socket.io-redis` rather than requiring the caller to remember to set some flag on the injected client.
