### ISSUE TITLE
Clients in same room from different node processes

### ISSUE THREAD

**Issue by aravindsrivats** [socketio/socket.io-redis#92]
When I try to get the socket.sockets.adapter.rooms array, it returns only the clients connected from the current process.  Is there a problem with the update?  It used to work for me in the last week.

**Comment by travellingprog** [comment]
@aravindsrivats  I'm not a Socket.IO contributor, but I happened to have come across this StackOverflow answer earlier that seems to imply that it is working like by design: http://stackoverflow.com/a/30986590/2051913

**Comment by fgodino** [comment]
I created a PR that adds this functionality and is up to date with the current Adapter. Check it out https://github.com/socketio/socket.io-redis/pull/109

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/commit/679e73ce6e88a50e418dcd865c4fb9d69aca6feb
