### ISSUE TITLE
Handle URLs properly

### ISSUE THREAD

**Issue by hgcummings** [socketio/socket.io-redis#93]
The [https://github.com/NodeRedis/node_redis](Node.js redis client) supports (and [explicitly documents](https://github.com/NodeRedis/node_redis)) fully-specified URLs, i.e. `[redis:]//[user][:password@][host][:port][/db-number][?db=db-number[&password=bar[&option=value]]]`.

The socket.io-redis adaptor can only handle URLs of the form `hostname:port`.

**Comment by hgcummings** [comment]
Thanks! The patch above is waiting for merge on PR #94. Hopefully someone can get to it soon.

**Comment by portepa** [comment]
That would be cool to see this patch merged.
Thanks @hgcummings for this fix.

**Comment by hgcummings** [comment]
Any chance of any movement on this? - It's becoming more inconvenient for me and I was hoping my PR would have been merged by now. Or is this blocked on issue #75?

Please let me know if there's anything I can do to help get the PR merged.
