### ISSUE TITLE
Do I have to use redis for socket.io cluster?

### ISSUE THREAD

**Issue by needforspeed** [socketio/socket.io-redis#98]
Hi there,

My goal is to have a nodejs cluster with sticky-session, the idea was from http://socket.io/docs/using-multiple-nodes/#

My use case doesn't require inter node communication. I plan to do a hash on incoming IDs and distribute them to one of the worker.  I see the socket.io-redis package from https://github.com/elad/node-cluster-socket.io, but I didn't see why it requires redis.

Can you please let me know the role of redis in the cluster? Can I use a map in the master instead of redis? 

Thanks in advance!

**Comment by artofspeed** [comment]
if u want to broadcast to a room, emit event to a socket that resides on another process, u need redis

**Comment by needforspeed** [comment]
@artofspeed Thank you for the reply. I don't do broadcast, so I don't think I need redis in my case

**Comment by darrachequesne** [comment]
Please re-open if necessary.
