### ISSUE TITLE
how to select database redis?

### ISSUE THREAD

**Issue by mvtcode** [socketio/socket.io-redis#99]
socket.io-redis default select database redis 0, i want select other database.
Help me, please!

**Comment by darrachequesne** [comment]
I think you'll have to provide your own custom redis client:
```javascript
var redis = require('redis').createClient;
var pub = redis(port, host);
pub.select(<your database index>, function() {
  io.adapter(adapter({ pubClient: pub })); // same with subClient
});
```

You could also provide `db` value in options (as documented [here](https://github.com/NodeRedis/node_redis#options-is-an-object-with-the-following-possible-properties)), yet it is not recommended:

```
db: null; If set, client will run redis select command on connect. This is not recommended.
```

**Comment by BridgeAR** [comment]
@darrachequesne running a select on your own is not better than providing the db option, so in that case I recommend using this. That it is not recommended is a [statement](https://groups.google.com/forum/#!topic/redis-db/vS5wX8X4Cjg) from @antirez. But as that statement is five years old and databases won't leave Redis anymore that statement might not be to valid anymore.

**Comment by darrachequesne** [comment]
@BridgeAR thanks for the clarification :angel: 

@mvtcode hope this help! Closing this now, please reopen if something is missing.
